### ISSUE TITLE
Advertising bar not working on iphone

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#10]
The site I'm using is http://www.yomobi.com/bis 

I don't know if the issue is that user is logged in. We need to find a different way of suppressing the advertising on the desktop besides checking if they are logged in.  We need to guarantee that ads always show up on the mobile devices.

**Comment by onaseef** [comment]
Advertising bar still doesn't show up consistently on the iPhone.  It shows up more consistently on android.  Often the bottom one will appear briefly before disappearing.  The top one will just be the blue bar, with no ad.

**Comment by gilbert** [comment]
The ads are set to show 100% on mobile pages now, so if they don't show up on iphone, the problem is on google's side.
