### ISSUE TITLE
Production Bug: Saving changes on a page doesn't work

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#101]
Log in to  http://www.yomobi.com as
un: ymtest@mailinator.com
pw: 123123

Click on the widget named: Category
Add a new page to the top level

Go to: http://www.landjob.com/Resume-Templates/Examples.aspx
Download this file: http://www.landjob.com/Resume-Templates/Templates/resume-template-chronological-01.doc
Copy the text from the .doc file into the page.  
First, notice the emulator doesn't update, even after you hit save.
Hit save, click the back button, then go back into the page, and you see the text you pasted in.
Now, if you make any changes and hit save, nothing is saved.

As an example, try to edit the page named: Category -> Problem with Save

**Comment by gilbert** [comment]
This bug has been fixed in master. You need to push to production.
