### ISSUE TITLE
Production Bug - Tab Bar doesn't update when I change the name of a widget that appears on it

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#104]
I had the Facebook widget on my mobile tab bar, than I renamed it to "Like Us", but the tab bar didn't update to reflect the new name.

**Comment by gilbert** [comment]
Which account did this happen on?

**Comment by onaseef** [comment]
molotovlounge

**Comment by gilbert** [comment]
Can you give me the password?

**Comment by onaseef** [comment]
molotovlounge@mailinator.com molotovlounge

FYI, the tab bar updates once I refresh. It just doesn't update automatically when I change the name of the icon.
