### ISSUE TITLE
Youtube Video Upload Bugs

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#106]
1. Youtube icon doesn't show up on the toolbar for the page editor. I'm guessing the image hasn't been added to the graphic
2. The "Add Youtube Video" dialog has the title: "Select an Image".  It should have the title: "Add Youtube Video"
3. Add a ? button which links to YoMobi help link:  help.yomobi.com/howtoembedyoutubevideo

**Comment by gilbert** [comment]
The icon is there. I added it to `jquery.wysiwyg.gif`
