### ISSUE TITLE
Firefox 3.6.24: Photo/Youtube embed bug in WYSIWYG

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#112]
On a PC, in Firefox 3.6.24, the Youtube and Photo upload embed wrong in the WYSIWYG editor.  The image uploads ,but all you see is a broken image link, and the video embeds, but all you see is a black square.  It looks fine in the emulator and on the phone, so the items are being properly embedded, but something specific to Firefox makes the WYSIWYG editor behave wrong.

Check email for image

Update: The images eventually appeared on the page, but the video remains a black box.

**Comment by gilbert** [comment]
I think the black box has to do with the "contentEditable" mode. That's the mode that browsers support so that all these wysiwygs are possible. IE seems to do the same thing... it could be that chrome just happens to load the video in an editable document.

**Comment by onaseef** [comment]
Actually IE7 on my PC shows the video image and even plays it in the WYSIWYG editor.  That's what I found odd. Only Firefox was the one that didn't work.

**Comment by onaseef** [comment]
This appears to be a firefox bug that is fixed in later versions.
