### ISSUE TITLE
IE7: Saving error after photo upload

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#114]
Use the "local" account.  

Go to page:  Newest -> My aname
Make any changes to the page and try to save. 
It reverts back to the original settings.

There must be some exception being thrown.

**Comment by gilbert** [comment]
I copied the widget data from your db and it seems to work fine. Is this happening on just that widget, or others too?

**Comment by onaseef** [comment]
It's happening with other widgets too.  
Try page: TestCat -> Error Page.  
1. Also, if I add a YouTube video, it only appears at the top of the page.

It is happening consistently with me in IE7.  The save doesn't work.  If you have time, we can do a remote session and I can show you.
