### ISSUE TITLE
If the type of file being uploaded in the photo upload dialog is invalid, we need a clean error message

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#116]
Try to upload a BMP file. You get an error message in 2 different places on the dialog that reads:

Error: -601, Message: File extension error, File 2.bmp.

Instead, we should catch the error and put a clean message like: You cannot upload a Bitmap file. Please select files with the following extension: png, jpg, jpeg, gif  (or whatever the valid extensions are).

Ideally, we'd exclude .bmp files from the file select dialog altogether.

**Comment by gilbert** [comment]
Those errors are the uploader library's internally handled errors and are undocumented. I can write code to catch that one specifically, but not in a generic way to cover all errors thrown and handled by the library.

**Comment by onaseef** [comment]
Catching that one error is a start.  Can you limit the acceptable input files to .png, .jpg, .jpeg, .gif?  I know it may not work with every file upload, but it doesn't hurt to limit the selection if possible in some of them.

**Comment by gilbert** [comment]
The accepted file list has been set to `jpg,jpeg,gif,png` since I first implemented the uploader. It looks like IE only accepts a filter called "Image Files", which is what the plugin probably uses to be able to filter anything at all.

**Comment by gilbert** [comment]
Actually, it's working fine in IE8. Is this only happening in IE7?

**Comment by onaseef** [comment]
I only have IE7, so that's all I've seen. I can't recall if it also happens on Chrome and Firefox and Safari.
