### ISSUE TITLE
Table tag not being stripped in a Category -> Page

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#119]
Table tags are stripped from a custom page on cut & paste, but not from a category -> page.  We need to make sure the same processing happens in both locations.

**Comment by gilbert** [comment]
They both call the same function. Can you give a content example that it's not working on?

**Comment by onaseef** [comment]
Use data from the local account
Go to http://www.namcc.org/prayertimes.php
Highlight the table and paste it into: About Us.  The tags get stripped properly
Now go into Newest -> My aname. Scroll all the way down to the bottom.   Paste the table there. It stays.  I've already pasted the table there twice to so you can see what I mean.
