### ISSUE TITLE
Menu Creation Broken

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#13]
check out un: tasteofethiopiaaustin@mailinator.com  pw: toeaustin

Click on the Menu widget and try to view it.  I added items under Meat Dishes and they all disappeared.  When I click on "Meat Dishes" it goes 2 levels down right away, rather than 1.

Here's what I did:

I created the new account. I started organizing the menu widget categories according to the menu for this place.  I added numerous items under Meat Dishes and then click "OK", they showed up. Then I went up a category and tried to navigate to "Vegetarian Dishes" and I couldn't get to it, so I did a refresh on the browser.  At that point, I could get to Vegetarian, but everything under Meat was lost.

When I click on Meat, it immediately takes me 2 levels into it, as I see from the bread crumb.  But there is no content. And clicking the "Back" button does nothing.

The data appears to be correct in the public database.  

I feel like this might be tied to issue #12.  Where there was weirdness going on when I tried to add more pages.

**Comment by gilbert** [comment]
The listed username / password is not working.

Edit: Nevermind, I must have copy/pasted wrong somehow.

**Comment by gilbert** [comment]
Should be fixed now.
