### ISSUE TITLE
New Collection Widget UI

### ISSUE THREAD

**Issue by gilbert** [onaseef/yomobi#132]
- `3 hours` New item list UI with selectable and drag & drop: http://jsbin.com/aweyo5
- `1 hour` New layout using a toolbar: -back button icon- | -new folder icon- -new item icon- | -data import icon- | -rename- -edit- | -delete-
- `1 hour` Rewiring all events

**Total time**: `5 hours`

**Comment by onaseef** [comment]
UI updates for Collection Widget changes.

Instead of a menu, we have a toolbar on top with the following:

-back button icon- | -new folder icon-  -new page icon- | -data import icon- | -rename- -edit- | -delete-

Since items can be reordered by drag and drop, we don't need the up/down arrows anymore.

**Comment by gilbert** [comment]
The toolbar is slightly easier than the menus, so the second step will only take 1 hour instead of 2. I still need to rewire the events to the new drag and drop events. Without the new "moving more than one item at a time" button, it will take 1 hour instead of 2.

I've updated the original post to reflect this.

**Comment by onaseef** [comment]
Can we make it to where the menu buttons can optionally have text next to the icon, so, for example, I might want to put "Add Folder" and "Add Page" or "Add Item" in the toolbar for those buttons, but for the rest, I just have icons.

So, for example the toolbar would look like:

[<-] | [$ Add Folder] [% Add Page] | [Edit] [Rename] [Delete]

**Comment by gilbert** [comment]
Sure, no problem.

**Comment by onaseef** [comment]
What's the status on this one?

**Comment by gilbert** [comment]
Going to start on this first thing tomorrow.

**Comment by gilbert** [comment]
What size icons are you planning to use?

**Comment by onaseef** [comment]
I'm thinking 16x16 or 20x20. Can the list adjust to different icons sizes?

**Comment by gilbert** [comment]
Yes. It only takes a few css adjustments.

This is ready to test on branch `collection`.
