### ISSUE TITLE
BUG: Color picker not persisting in General Settings Page

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#139]
See <a href="https://docs.google.com/open?id=0B2qHfsz2HClsN2YwMDNmNzktNDYyNC00MjNmLTk5NjktMjlmOTEzMTZlNDNj">this picture.</a>.

Here's how you reproduce it:
- Click on general settings
- Set a header color and hit save
- Hit Save again.
- The color is now gone.

**Comment by gilbert** [comment]
This is old. I've added the header text and fixed some bugs since this was opened. Please reopen if it occurs again.
