### ISSUE TITLE
Add 'leaf' to the class description for leaf items in category-like widgets

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#14]
I'm making css changes, and found that with category-like widgets (Services, Menu, etc), the leaf items don't have a distinct class, like the subcategory items do.

Subcategories have the classification:  -div class="category item c1" data-id="c2">Breakfast</div-

While leafs currently have the classification: -div class="item c1"><div class="name">Sambusa</div>...</div-

Please change the leaf on all category-like widgets to have the classification:  -div class="leaf item c1">...</div-

**Comment by gilbert** [comment]
That's the way it's supposed to be. You target both categories and items by styling the `.item`. Then you target categories specifically by styling `.category.item`. Anything in that selector overrides anything in the `.item` selector.

You'll see something like this in `mobile.scss` line 273:

```
.page .content.page_tree {
  .item { /* ... */ }
  .category.item { /* ... */ }
}
```
