### ISSUE TITLE
Add Header Text Color Picker

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#140]
I realize that if someone picks a light color for their header background, they need to be able to select a different color for the header text, so we need a second color picker for the header text.

Just add it below the header background color picker:  Label: Header Text:

**Comment by gilbert** [comment]
This should be taken care of.

**Comment by onaseef** [comment]
I did a sync and I'm not seeing this change.  Has it been pushed?

**Comment by gilbert** [comment]
Ah sorry, I forgot to push it.
