### ISSUE TITLE
Update the UI for collection widgets - list update, reposition buttons

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#142]
- `3 hours`  - New item list UI with selectable and drag & drop: http://jsbin.com/aweyo5
- Instead of a menu, we have a toolbar on top with the following:
  - back button icon- | -new folder icon- -new page icon- | -rename- -edit- | -delete-
  - Since items can be reordered by drag and drop, we don't need the up/down arrows anymore.

**Comment by gilbert** [comment]
This is a duplicate of #132
