### ISSUE TITLE
Styles not being stripped when pasted in custom page

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#143]
The style tag should be stripped on all items pasted in pages.  Here's some html. When I paste it, it doesn't strip the -styles- tag.

Copy the html below as is (without going into edit mode), then paste it into a custom page and look at the html.

<hr>

<h3><img src="http://s3.amazonaws.com/yomobi-logos/wphotos/483-original?1326260126" class="yo yo-none" data-size="100" style="float: none; max-width: 100%; width: 360px; height: 60px; "><span>Served with chips &amp; salsa, and with your choice of french hoagie, whole wheat hippie bun or ciabatta bread.</span></h3><h3><span>(<img src="http://s3.amazonaws.com/yomobi-logos/wphotos/487-original?1326261830" class="yo yo-none" data-size="70" style="text-align: left; float: none; max-width: 100%; width: 30px; height: 30px; ">Indicates Vegetarian)</span></h3><div><hr></div><div><h3><b>&nbsp;</b><img src="http://s3.amazonaws.com/yomobi-logos/wphotos/488-original?1326262607" class="yo yo-none" data-size="70" style="float: none; max-width: 100%; width: 30px; height: 30px; ">Insalata Caprese Sandwich<b>&nbsp;</b><span>(Served Hot).......................... 5.95</span></h3><div><h3><span>Mozzarella, tomato, onion and fresh basil sprinked with capers, dressed with extra virgin olive oil and balsamic vinaigrette.<br></span><p></p><p class="MsoNormal"></p><hr><p></p><p class="MsoNormal"></p><p class="MsoNoSpacing">Monkey Nest Special&nbsp;</p><p class="MsoNoSpacing"><span>(Served Hot)........................... 6.95</span></p><p class="MsoNoSpacing"><span>Grilled chicken breast dressed with fresh basil, garlic, cranberries, tomato, red onion and capers, in a honey mustard dressing</span></p><p class="MsoNoSpacing"></p><hr><p></p><p class="MsoNoSpacing">Tuna-Provolone Sandwich<span>(Served Hot)........................... 6.50</span></p><p class="MsoNoSpacing"><span>Tuna salad in a creamy feta cheese dressing, made with dill and served with tomato, lettuce, red oni</span><span>on and provolone cheese</span></p><p class="MsoNoSpacing"></p><hr><p></p><p class="MsoNoSpacing"><img src="http://s3.amazonaws.com/yomobi-logos/wphotos/488-original?1326262607" class="yo yo-none" data-size="70" style="text-align: center; font-size: 16px; font-weight: normal; float: none; max-width: 100%; width: 30px; height: 30px; "><span>Hummus Peace Sandwich</span><span>&nbsp;&nbsp;&nbsp;</span></p><div><span>......................</span><span>....................... 5.95</span></div><div><span>Hummus and feta cheese with cucumbers, lettuce, tomato, capers, dill, toasted sesame seeds and balsamic vinegar</span><br></div><p class="MsoNoSpacing"></p><hr><p></p><p class="MsoNoSpacing">Pastrami Sandwich</p><p class="MsoNoSpacing"><span>(Served Hot)........................... 6.95</span></p><p class="MsoNoSpacing"><span>Pastrami, Swiss cheese, sauerkraut, Dijon mustard and horseradish</span></p><p class="MsoNoSpacing"></p><hr><p></p><p class="MsoNoSpacing">Spicy Roast Beef Sandwich<span>(Served Hot)........................... 7.50</span></p><p class="MsoNoSpacing"><span>Roast beef, Swiss cheese, tomato, lettuce, red onion, mayonnaise, horseradish and red pepper sauce</span></p><p class="MsoNoSpacing"></p><hr><p></p><p class="MsoNoSpacing">Turkey-Provolone Sandwich<span>&nbsp;</span></p><p class="MsoNoSpacing"><span>............................................. 6.95</span></p><p class="MsoNoSpacing"><span>Turkey breast, provolone cheese, tomato, lettuce, red onion, mayonnaise and Dijon mustard</span></p><p class="MsoNoSpacing"></p><hr><p></p><p class="MsoNoSpacing">Italian Panini&nbsp;</p><p class="MsoNoSpacing"><span>(Served Hot)........................... 6.50</span></p><p class="MsoNoSpacing"><span>Sliced Mozzarella, tomato, fresh basil and prosciutto, dressed in extra virgin olive oil</span></p><p class="MsoNoSpacing"></p><hr><p></p><p class="MsoNoSpacing"><img src="http://s3.amazonaws.com/yomobi-logos/wphotos/488-original?1326262607" class="yo yo-none" data-size="70" style="font-size: 16px; text-align: center; float: none; max-width: 100%; width: 30px; height: 30px; ">Italian Spinach Panini</p><p class="MsoNoSpacing"><span>............................................</span>&nbsp;<span>6.50&nbsp;<o:p>/o:p</span></p><p class="MsoNoSpacing"><span>Fresh spinach, sliced mozzarella, sliced black olives, sprinkle of oregano, garlic and parsley, with balsamic vinegar and extra virgin olive oil</span></p><p class="MsoNoSpacing"></p><hr><p></p><p class="MsoNoSpacing"><img src="http://s3.amazonaws.com/yomobi-logos/wphotos/488-original?1326262607" class="yo yo-none" data-size="70" style="font-size: 16px; text-align: center; float: none; max-width: 100%; width: 30px; height: 30px; ">Kid’s Grill Cheese</p><p class="MsoNoSpacing"><span>(Served Hot)........................3.50</span></p><p class="MsoNoSpacing"><span>Grilled cheddar cheese and white bread</span></p><p class="MsoNormal"><o:p>&nbsp;/o:p</p><p class="MsoNormal"><o:p>&nbsp;/o:p</p><p></p><p class="MsoNormal"></p><p class="MsoNormal"><span><br></span></p><p></p><p class="MsoNormal"><span><br></span></p><p class="MsoNormal"><span><br></span></p></h3></div><div><br></div></div>

**Comment by gilbert** [comment]
I don't see any style tags in that html. Do you mean style attributes?

**Comment by onaseef** [comment]
I did mean style attributes.

**Comment by gilbert** [comment]
It works for me. I copied the content, not the html directly.

With the addition of the html editing button, and the move to target developers, I wonder if we should remove style stripping altogether. It would be annoying to have custom styles stripped whenever you paste text.

**Comment by onaseef** [comment]
Is there a better editor than the one we're using that will allow us to strip all the HTML just from the pasted text?

**Comment by gilbert** [comment]
Strip all html, as in no tags whatsoever?

Stripping html is not really a problem that wysiwygs try to address, though some do try to strip data for specific cases, such as word documents.

**Comment by onaseef** [comment]
When the user pastes text into the WYSIWYG editor, I'd like to strip all the HTML, but just from the pasted text, minus the img tag, in case they copy and paste images into the WYSIWYG. It will help solve problems the users have when they paste. The goal is to make it was user friendly as possible. 

More than one user has had issues with how things show up when they are pasted. They don't understand HTML, so they think the problem is with the WYSIWYG editor because they don't realize that by copying text from a web page, they're also copying html tags, etc.

**Comment by gilbert** [comment]
As we've discussed before, the browser doesn't give the info on what text has been pasted and what hasn't. To do this manually would be a very large effort.

**Comment by onaseef** [comment]
Yes, I know we discussed it before, that's why I asked if there's a better editor out there than the one we're using.
