### ISSUE TITLE
Re #133 - Color picker in advanced settings panel not set the first time we go to it

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#145]
Re item: #133

If the user hasn't set a custom color for the heading background and label, when we first go to advanced settings, the color pickers don't have the default site colors in there. 

If a custom value isn't set, we should default the header and text colors to the system default colors.

**Comment by gilbert** [comment]
The problem is you can't reproduce the default header color using the color picker. If we default it to a certain color, then when the user clicks "save settings" without changing anything, the header will become a different gradient.

**Comment by onaseef** [comment]
Right now we're using a background image. I think I'll just change it to where by default we use a background color and I'll pick a color that is similar to what we have now.  Would that be a lot of changes on the back end?

**Comment by gilbert** [comment]
Not at all.

**Comment by onaseef** [comment]
Here's the default header bar gradient color: #2a426a

**Comment by gilbert** [comment]
Fixed
