### ISSUE TITLE
PRODUCTION: File upload tool doesn't handle errors gracefully

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#147]
I tried to upload a file, and I got <a href="https://docs.google.com/open?id=0B2qHfsz2HClsOGIyYzk4ZDctZWI5Yi00OWVhLWI5OGEtMmQ1NDlkYjY1MTZk">this error</a>. After the error, the UI just hangs.

We need to handle exceptions with a catch-all.  

In this instance I got the error because my Amazon key is wrong. A user had a similar problem where the UI hung when they tried to upload a picture to a page, so we need to make sure to capture exceptions and provide meaningful messages when possible and clear out the UI so they can try again.

**Comment by onaseef** [comment]
Is there an updated on the status of this bug?

**Comment by gilbert** [comment]
That _is_ handling the error gracefully. The only bug is that the ui locks up, which I just fixed.

It's already handling two specific errors, uploading bitmaps and invalid file types. For all other unrecognized errors it just prints them to screen. This is so users can report the bug, as those errors aren't supposed to happen in the first place.
