### ISSUE TITLE
Site Manager: Active Signup Keys

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#152]
If I press the Generate Signup Keys button, it keeps adding to a list of signup keys. There's no way to get rid of the signup keys. There should be a single text field, and when I click Generate Signup Key, it should appear in that field for copy and paste. If I click Generate again, it should overwrite the previous key.

**Comment by gilbert** [comment]
Please label the issues "Site Manager" instead of "Site Settings".

This wasn't in the specs, so I just did whatever took the least amount of time.

Incidentally it supports multiple keys at once, so you can email two keys to two users. Do you want to remove this feature?

**Comment by onaseef** [comment]
It can still support multiple keys, but only one should be visible at a time. So, for example, when I want to send a site key to one user, I'll click "Generate Site Key" and then I'll send it to that user. If I want to send another site key to a different user, I'll generate another one and send it. 

I'm thinking the better UI is that Generate Site key pops up a dialog with some instructions and the key so that way, the site key doesn't remain visible in the Site Manager viewer, which might be confusing, especially if it expires after it is used once. Then the user will have to remember which ones have been sent and which haven't

**Comment by gilbert** [comment]
Expired keys don't display.

I can do the text box no problem. The dialog would take an additional hour.

**Comment by onaseef** [comment]
Do keys expire when used, or after a certain amount of time?

I need to design the UI based on how it works in the back end. I'd prefer to use an inline text box, bu I think we need to go with a dialog box to ensure the site key list doesn't grow indefinitely and to ensure there isn't any stale keys in the view.

**Comment by gilbert** [comment]
They expire after one use. There's no time limit, though it's possible to set one. Expired keys don't display in the list.

**Comment by onaseef** [comment]
We need to go with the dialog because if we use the list view, then the admin might send the same key to more than one person, and that will cause problems. The only way to ensure the same key isn't sent to more than on person is to discard it after it's be displayed for copy.  If you can think of a way to prevent the admin from sending the same key to 2 different users without having the key only appear in a dialog box, I'm open to suggestions.

**Comment by gilbert** [comment]
Maybe we can have a link next to the button that says "Display active keys". When a user clicks that, all keys will be shown below like they are now. Otherwise they'll stay hidden. Clicking the display link again will hide them all.

When a user generates a new key, only that key will show up (unless the user has already clicked the display link).

**Comment by onaseef** [comment]
I don't see an advantage of being able to see the other keys. It clutters the UI in my opinion. 

The way I think it works best is, when I'm ready to assign the site to the owner, I click on  Generate Signup Key, copy the key from the dialog and then mail it to the person. Once I send the link to the owner, I don't care about it again. If the owner misplaces the key I just generate another key and send that to them.

That feels clean and simple.

**Comment by gilbert** [comment]
Ok, so keys will show once generated and after a page refresh won't show again?

**Comment by onaseef** [comment]
I would say the key should show up in a dialog rather than on page itself. That way we can also put some instructions in the dialog and once they hit close it's gone. No need to worry about refresh or not.

**Comment by gilbert** [comment]
What information do you want to put in the dialog? I'm not sure if you noticed, but there's a help bubble next to the generate key button.

**Comment by onaseef** [comment]
You can leave it as a text field in the view in that case. No need for a dialog. They're admins so they should be able to get it. Also, if they hit "Generate Signup Link" again, it should just replace the current link that in the text field.

Also, the field would need to disappear on refresh.

**Comment by gilbert** [comment]
Ok, got it.
