### ISSUE TITLE
Site Manager: Signup page for signup link should exclude site type and captcha

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#153]
Since the user is signing up with the signup link, the site already has a known type.

We also don't need the captcha because the only way to get a access to this page is with a valid signup link sent from one person to another.

**Comment by gilbert** [comment]
The captcha is still needed. Without captcha, a malicious user could write a bot that generates keys and uses them to sign up.

Hiding the site type field is fine.

**Comment by onaseef** [comment]
If signup keys can end up not being associated with a specific account, than we need the site type to remain. Otherwise the site would be created with no associated site type. You can just leave it all the way it is.
