### ISSUE TITLE
Site Manager: Invalid signup key should show an error page

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#154]
I modified the signup key to a random number, and I still got to the signup page.  What happens after the user hits Sign Up, when the key is invalid? There's no site to associate with, so there will be a problem.

**Comment by gilbert** [comment]
In that case their account would be created and they would be taken to the site wizard.

**Comment by onaseef** [comment]
So if there's no valid account associated with the key, it acts as if the key wasn't there at all?

**Comment by gilbert** [comment]
Correct. The error page is needed more now since we're going to hide the site type.

**Comment by onaseef** [comment]
In that case, we might just keep it exactly the way it is with the site type and captcha there.
