### ISSUE TITLE
Site Manager: Create new site just hung

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#159]
Using the account: local
un: lt@mail.com
pw: 123123

I tried to create the account aatest3 (which already exists). And then it just hung.  

Here's the error:

Started POST "/sites" for 127.0.0.1 at 2012-01-24 21:43:58 -0600
  Processing by SiteManagerController#create as 
  Parameters: {"site"=>{"title"=>"aatest3", "url"=>"aatest3", "type"=>"32"}}
  User Load (1.0ms)  SELECT "users".\* FROM "users" WHERE "users"."id" = 1 LIMIT 1
Completed 500 Internal Server Error in 181ms

NoMethodError (You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.+):
  app/controllers/site_manager_controller.rb:159:in `couchdb_exists?'
  app/controllers/site_manager_controller.rb:29:in`create'

Rendered /usr/local/Cellar/ruby/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-3.0.8/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.5ms)
Rendered /usr/local/Cellar/ruby/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-3.0.8/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (4.6ms)
Rendered /usr/local/Cellar/ruby/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-3.0.8/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (11.9ms)

**Comment by gilbert** [comment]
Creating a site whose url already exists works fine for me. Have you tried restarting the server?

**Comment by onaseef** [comment]
I did restart my server and then it worked fine. However, are we catching those types of exceptions so things won't hang?

**Comment by gilbert** [comment]
Nope. Pushing to production restarts the server automatically, so this sort of thing wouldn't happen in the first place.

**Comment by onaseef** [comment]
Okay, well if there's nothing to catch, then we can close it.
