### ISSUE TITLE
Site Manager: Site access and site collaborator lists should be a fixed height with a scroll bar

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#162]
Right now, they just keep growing as new list items are added. They should be a fixed height with a scroll bar.

**Comment by gilbert** [comment]
This is fixable with css styling. I did not budget styling into my budget.

The `height` and `overflow: auto` properties should be useful for this.

**Comment by onaseef** [comment]
Awesome. I'l handle it than.  Thanks!
