### ISSUE TITLE
Collection UI: Can the li in the ul be a table rather than divs to ease formatting

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#165]
I've attached a screenshot <a href="https://docs.google.com/open?id=0B2qHfsz2HClsMzVkNzE2YTQtMTRjOS00ZDY0LWJiZDgtYWE5ZTg5MDc3YjY0">here</a> and <a href="https://docs.google.com/open?id=0B2qHfsz2HClsMzFjYjQ1NzEtZDI1ZS00ZDI2LTliZGMtZWM0MmUxYzNkNzVm"> here </a> for you to see how it looks when the name is long. What I want is the icons to be in column 1 and the text to be in column 2 so it doesn't wrap under the icon and the move arrows to be in column 3 so it can be vertically centered.

**Comment by gilbert** [comment]
Tables are cumbersome and add a lot of markup. Try this instead:

```
.name {
  padding: 6px 10px;
  float: left;
  width: 260px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: no-wrap;
}
```

**Comment by onaseef** [comment]
I think this is fixed.
