### ISSUE TITLE
Adding script to show the phone number if the user is browsing to a Yomobi site from a non-phone

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#166]
How much work would it be to add a script that goes to a phone number page if a user clicks the "Call Us" button when browsing a yomobi site on a device that isn't a phone, such as a tablet or a desktop computer.  

If they click on Call Us on a phone, it automatically dials the number. If the device isn't a phone, it goes to the phone number page instead.

**Comment by gilbert** [comment]
Up to 2 hours.

**Comment by onaseef** [comment]
We can go ahead and do this one.  How would the script work?  How would it distinguish a device the can handle the tel: extension verses on that doesn't?

**Comment by gilbert** [comment]
If the device doesn't support the `tel:` href, then the device won't do anything (as far as I know). In that case, the code will bring up the phone number page.

**Comment by gilbert** [comment]
Do you have an ipad or tablet to test this on?

**Comment by onaseef** [comment]
Yes I do. I can test it tomorrow or when it is finished. In theory, it should also work on any regular computer since they don't support tel: and we can always browse to the site and click on call is.
