### ISSUE TITLE
Add a hide-widget checkbox that hides a widget from the mobile site even if it has data

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#167]
How much work would it be to add a "Hide Widget" checkbox that allows the user to add a widget to their site, but hide it from being displayed on their preview or live site. 

The goal would be to hide a widget without having to delete it so that they can continue to work on it or update it and then publish it later.

**Comment by gilbert** [comment]
This would take up to 2 hours.

**Comment by onaseef** [comment]
I need to figure out the UI for this before we proceed.

**Comment by onaseef** [comment]
This widget is only for category-like widgets. The "Deactivate" checkbox should appear below the  "Click here to start editing' button.  It should have a ? help button next to it.

**Comment by gilbert** [comment]
Available for testing on branch `hide`.

**Comment by onaseef** [comment]
We need a different icon and status message for hidden widgets than for ones that lack information.  Right now it uses the same warning icon and "missing info" message, which will be confusing.

I can provide you with a new icon, but I will need you to update the icon and message associated with hidden.

**Comment by gilbert** [comment]
Will do.

**Comment by gilbert** [comment]
Ok, done. For the new icon you need to name it `widget-manually-hidden.png` and put it in the `public/images/ui/` folder.

**Comment by gilbert** [comment]
Never mind, I just saw you added an image to the repo. I'll use that one.
