### ISSUE TITLE
Adding a field to the general settings for a slogan

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#168]
How much work would it be to add a text field to the general settings page that lets the user enter a slogan.  The field would appear below the site name.  We could also add the slogan to the wizard. 

It would show up in the code as follows (you'll need to put the field in edit mode to see the html).  See a sample graphic <a href="https://docs.google.com/open?id=0B2qHfsz2HClsNjg4NThjMTEtMTA2My00Yjk1LTkzODctZWYyZDhjMTE0NWE5">here</a>.

<div class="company-info"><table><tbody><tr><td style="
    vertical-alight: top;
"><img class="logo" src="http://s3.amazonaws.com/yomobi-logos/logos/yomobi_mobile?1314747737"></td><td class="name"><div class="name" padding-bottom:="" 10px;="" "="">YoMobi</div><div style="
    font-size: 60%;
    font-style: italic;
" class="slogan">This is the slogan text</div></td></tr></tbody></table></div>

**Comment by gilbert** [comment]
This would take up to 2 hours of work.

**Comment by gilbert** [comment]
Done. This will require a `rake db:migrate` and a server restart.
