### ISSUE TITLE
Add a flag to the back end that will hide advertisements for certain sites

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#169]
How much effort would it be to add a flag to the backend database that I can manually set to hide ads from certain sites.  I don't want anything in the front end right now, and this is somewhat urgent so I want a quick solution that can later be built on.

Basically, I'd like to add a field to to the non-public database that says lets me specify a site and say it is ad-free.   What suggestions do you have for the design of it?

**Comment by gilbert** [comment]
If it's backend only, I can add a no-ad column and provide a checkmark in the admin panel. This would only take 1-2 hours.

**Comment by onaseef** [comment]
For now it is on the backend only, since there's no infrastructure in place. Which admin panel are you referring to?  Even though it's backend only, I would like it designed so that when we automate the process later in the front end, it can easily integrate with the new column without having to redesign anything.

Also, the flag would need to be associated with individual sites, not user accounts, since one user account can be associated with multiple sites.

**Comment by gilbert** [comment]
Yes, the flag would be a column in the company (called site in the frontend) table. It will be easy to automate it later.

The admin panel I'm talking about is http://yomobi.com/admin/companies

**Comment by onaseef** [comment]
Sounds good. Thanks for the explanation. I just wanted to make sure it was site specific.

**Comment by gilbert** [comment]
Done. The "Premium" checkbox is right under the "Edit Company" title when you edit a company in the admin panel.
