### ISSUE TITLE
Phone Page: Creates invalid link on iPad

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#172]
On the iPad, the new phone page for issue #166 causes the <a href="https://docs.google.com/open?id=0B2qHfsz2HClsZGIyMGFjNjQtNjM5YS00MTg4LWJiYjktMDRhYmY3YzFmMDE1">following problem</a>. Instead of going just to the page, it seems to direct the browser to some invalid link.  I think the issue might be that the number is url-encoded, because on the kindle fire, clicking on the link brings up a garbled phone number.  

Also, I updated the page to make the telephone number a "tel" link and clicking on that link works fine on the ipad. So something about the way the link is formed when clicking on the call us icon is incorrect.

**Comment by gilbert** [comment]
It turns out I was wrong about this. Browsers that don't support the `tel:` protocol won't simply ignore it, but open an error message.

One way to get around this is to make the phone widget always open the page, and have the phone number clickable. That way browsers that don't support it (ipad, for example) won't see the error message unless the user actually clicks on the number.

**Comment by onaseef** [comment]
The ipad supports the tel link fine. If you click on a tel link, it brings up a context menu and asks you if you want to add the number to your contact list. I had converted the phone number on the phone page to a tel link, and when I get to it, after seeing the error message upon clicking on the button icon, the link works fine.  See <a href="https://docs.google.com/open?id=0B2qHfsz2HClsODIzYTZmYjItY2JmNi00ZGNlLTlmMzctNWNkYmQ3MTk5NmU2">here</a>.

The issue is that the link that's associated with the button itself is not valid.  It has some weird format.

**Comment by gilbert** [comment]
Can you try it now?

**Comment by onaseef** [comment]
I tried it and it worked well on the different platforms.  Interestingly enough, on the ipad, it never makes it to the page. The ipad just brings up the context menu and asks if you want to add the number to a contact or copy the number.  So you can end up seeing the number by selecting "add to contact".  Ideally for the ipad, we'd go straight to the page.  Is that possible?

If it's a lot more work, it's acceptable for now.

**Comment by gilbert** [comment]
Ok, I added a special case for the ipad. Tell me if it works.

**Comment by onaseef** [comment]
It worked. Good work!  I had to fix a typo, so you'll need to refresh your repository to get the fix. 

Thanks!
