### ISSUE TITLE
Question about: rake db:migrate 

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#175]
If you make a change that requires a db migrate on production, is the procedure
1. Push the changes to heroku  (which breaks the system)
2. Run rake db:migrate (which fixes the break)

Or is there a way to do it that doesn't involve breaking the system first?

**Comment by gilbert** [comment]
There's no way to avoid the "break". To minimize the time you can run the two commands in the same line:

```
git push heroku master; heroku run rake db:migrate --app yomobi
```

This will run the second command as soon as the first one is done.
