### ISSUE TITLE
Photos associated with pages got messed up

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#176]
Somehow the photos associated with one site got mixed in with photos associated with another site.  I was testing out the collection changes, and I wanted to see if they were backwards compatible so I linked my local account with a production account. Today, I discovered that some of the photos on the production account were changed to random other photos.

What might cause this? Now I'm concerned there might be a bug that will rear its head when multi-site is enabled.
How are photos associated with pages?  
Is there a possible design flaw?
Will this affect multi-site?

**Comment by gilbert** [comment]
The photo urls are stored in the public database. If you upload a photo on your local machine, it actually gets uploaded to amazon, and the url pointing to it gets stored in the public database. If you link your account to a production account, then changing photos change it in production as well.

What account had the changed photos? Were they photos you've never seen before? Are you the only one who has access to that account?

**Comment by onaseef** [comment]
To answer your questions:
1. The connecther account had the changes images
2. The photos were ones I had uploaded to the ymtest account.
3. There is one other person who has access to the account, but she didn't make any changes and hasn't touched the site in a while.

Is it possible that the images don't get unique names when they are uploaded? Perhaps the newly uploaded images replaced the others because they overwrote them by having the same name? Because the image formatting (size, location, etc) was exactly the same in connecther site. It was just a different image in place of the original one.

As background: 

I use the ymtest account for local testing.  After the collection editor updates, I connected to the connecther account to test if the data would show up properly in the list. Not all of the images changed.  Some of them did, while others stayed unchanged.

**Comment by gilbert** [comment]
Each uploaded photo is named with respect to its database id. So, in production, the uploaded photos start with id 1, and increment with each new upload, regardless of account. They have the format:

```
`wphotos/{ id }-{ style }`
```

So the very first upload thumbnail would have the filename:

```
`wphotos/1-thumb`
```

Thus it's possible that a new local upload would have an id that already exists in the production database. This is where the random photos would come in.

**Comment by onaseef** [comment]
So both test and production are uploading to the same bucket in AWS? And each one uses its own database counter to keep track of the last image id?

If so, it means that any future uploads I make to test may overwrite existing images in production even though I am not connected to production or editing anything in production. It's all just a matter of when I happen to upload an image?

Is that correct? If so, this needs to be fixed.

**Comment by gilbert** [comment]
To fix this you'll need to change your configuration. Right now you're using the production bucket:

```
export LOGO_S3_BUCKET='yomobi-logos'
```

You need to sign into the [AWS console](http://aws.amazon.com/console/), create a new bucket, and replace `yomobi-logos` in the line above with the new bucket name.
