### ISSUE TITLE
Adding a toolbar between the header and the main content of the home page

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#181]
I'd like to add a toolbar between the header and the main section of home page.  It would have links, including;

About Us, Why Mobile, Business Opportunities, Help

The Why Mobile and Business Opportunities pages would be on a page on the main site, similar to the help and about us pages.  

How much time would this take?

**Comment by gilbert** [comment]
Without styling this would only take an hour.

**Comment by onaseef** [comment]
1. How would it look without styling?  
2. Does adding the toolbar also including adding the Why Mobile and Business Opportunities pags on the site?  Obviously I'll fill in the content for the page, but the page itself needs to exist.

**Comment by gilbert** [comment]
1. Boxes with text in them.
2. Yes

**Comment by onaseef** [comment]
Go ahead and create a new branch for this change and implement it.

**Comment by gilbert** [comment]
Which pages do you want this new bar to show up on?

**Comment by gilbert** [comment]
I added the bar. Let me know what pages you want it to not show up on, if any.

**Comment by onaseef** [comment]
It should only show up when the user is not logged in. The bar should not appear when the user is logged in.

**Comment by onaseef** [comment]
Hi Gilbert,

Isn't the toolbar normally done with an <ul><li> structure? I notice ours is a table. What is the reason for that?

Thanks,
Omar

**Comment by gilbert** [comment]
I thought you might want the table layout. I can switch no problem if you want. Just fyi, it's more of a nav bar than a toolbar.

**Comment by onaseef** [comment]
I already switched it on my local computer, so no need to do that. Just wanted to know if there was a technical reason for the choice.

**Comment by gilbert** [comment]
This is what I came up with for `.landing-bar` in `signup.scss`. Do you think this looks ok?

``` scss
.landing-bar {
  @extend .signup-bar;
  a, a:visited { color:$main-color !important; }
  td { text-align: center; width: 25%; } /* <--- I added this line */
}
```
