### ISSUE TITLE
The link associated with the phone page looks odd on the kindle fire

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#184]
What is the tel link that is generated when the user clicks on the Call Us button?  

For some reason, on the kindle fire, the link looks URL encoded, so when a user clicks on it, it brings up the "Create Contact" page and inserts a garbled looking number in the phone field.

I just want to make sure the link isn't url encoded unnecessarily, so the customer won't have a bad experience when click on it on their tablet.

**Comment by gilbert** [comment]
Nope, the url is not encoded at all.
