### ISSUE TITLE
Create url subdomains for accounts 

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#187]
How much work would it be to do something like this:

http://www.robbyonrails.com/articles/2009/01/11/subdomain-accounts-with-ruby-on-rails-explained

So, users could access their account via yomobi.com/<myname> or <myname>.yomobi.com

The latter would allow us to make it so people could map their own subdomain to yomobi and seamlessly transition to their yomobi mobile site as if its URL was still their own.  Kind of like what we're doing with help.yombi.com

**Comment by gilbert** [comment]
Is it necessary for users to be able to access their account through *.yomobi.com? I can see it being useful if they access mobile sites through *.yomobi.com, but not actual accounts.

Either way this will require heroku's [custom wildcard domain add-on](http://addons.heroku.com/custom_domains).

**Comment by onaseef** [comment]
I meant access their mobile sites, not access their accounts. So they'd edit their site by logging in to yomobi.com, but they could access their mobile site with <name>.yomobi.com, which would allow them to map their own subdomain to <name.yomobi.com> so it looks like they are on their own domain.  I'll add the additional feature for $5 a month.

How long would that take?

**Comment by gilbert** [comment]
Ah, ok. This would take up to 3 hours to both implement and search & remap spots in the code where mobile url are handled.

**Comment by onaseef** [comment]
FYI, I'd like both yomobi.com/mysite and mysite.yomobi.com to work. The latter is only in case the user decides they want to map the second format to their domain. Is that more work?

**Comment by gilbert** [comment]
Actually, that'd be less work. Only 2 hours in that case.

**Comment by onaseef** [comment]
Please implement it

**Comment by gilbert** [comment]
I will get to this tomorrow.

**Comment by gilbert** [comment]
Ok, this is ready on branch `subdomains`. To test on your local machine you will need to add additional subdomains to your `/etc/hosts` file for each subdomain you want to test. Unfortunately you can't specify a wildcard.

Before pushing to heroku make sure you installed the wildcard subdomain add-on. I would double check [these docs](http://devcenter.heroku.com/articles/custom-domains) to make sure the `yomobi.com` domain is set up to work with subdomains on heroku.

**Comment by onaseef** [comment]
What am I supposed to add to /etc/hosts to get it to work?

**Comment by gilbert** [comment]
I recommend the following:

```
127.0.0.1 www.local.host
127.0.0.1 sub1.local.host
127.0.0.1 sub2.local.host
# etc...
```

With this setup, you can treat `www.local.host` as a replacement for `www.yomobi.com`

**Comment by onaseef** [comment]
Thanks.  If the changes you made for this branch were pushed out to the production server without the wildcard plugin from heroku, will that break anything? i presume an attempt to go to mysite.yomobi.com would just fail because it doesn't resolve, but yomobi.com/mysite would still work. Is that correct?

**Comment by gilbert** [comment]
That's correct. The subdomains will fail, but it really shouldn't break anything else.

**Comment by onaseef** [comment]
You can go ahead and merge the branch with master in that case
