### ISSUE TITLE
Merge subdomains branch with master

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#190]
You can go ahead and merge the branch with master in that case

**Comment by gilbert** [comment]
Done.

**Comment by onaseef** [comment]
Have you synched the changes? I'm not seeing it show up in my history when I sync.

**Comment by gilbert** [comment]
It snuck itself in there somehow.

https://github.com/onaseef/yomobi/commit/a84131747235474a60a2ca17ee27c5fb7a1789de

**Comment by onaseef** [comment]
So it's been merged into master for 4 days now?

**Comment by gilbert** [comment]
Seems that way. I didn't merge it though.
