### ISSUE TITLE
Pull in RSS feeds to auto-synch content on mobile with desktop site

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#192]
How much effort would it be to add a feature that allows us to pull in RSS feeds so that the mobile site auto synchs with another site?

I'd like a time and cost estimate for a potential customer.

**Comment by gilbert** [comment]
Ah, do you mean like an RSS widget that would input an rss url, and display its contents in the mobile site?

**Comment by gilbert** [comment]
A widget like that would probably take 4 hours to implement.

**Comment by onaseef** [comment]
I believe the goal would be to update the mobile site content based on the content of the desktop site. So, for example, you'd update a blog page with the latest blog, or you could link a specific desktop page to a mobile page to keep the mobile page up to date with changes on the desktop side. 

When you say an RSS widget, what do you mean by that? What would its content look like on the mobile site?

**Comment by gilbert** [comment]
RSS feeds are xml, so you can style it however you want. An RSS widget would look like an about us widget. On the builder, instead of a wysiwyg editor, there will be a single text field for an RSS url. On the mobile site, upon clicking the icon you'll get a list of posts that look like a collection widget. Clicking one of these posts will take you to another page (like a collection widget), displaying the post's html content.

**Comment by onaseef** [comment]
We'd need to have options I imagine like "sort order" and "maximum posts" as well.

What would be a way of updating a mobile site from a desktop site? Would we need to do something like have a field where the user can associate a mobile page with a desktop page and then we'd check every so often to see if the content has changed?  I'm just curious how it might work.

**Comment by gilbert** [comment]
That's up to the RSS feed itself. Normally they are ordered by latest post first, and don't show all posts.

**Comment by onaseef** [comment]
I'm thinking the RSS widget would look more like a Category widget in design.  

We'd allow the user to pull multiple RSS feeds into a single widget, so instead of a single field in the editor we'd have the same list tool we're using for Collection widgets and a toolbar on top with "Add RSS Field" and <Delete Icon> & <Edit Icon>. 

The Add/Edit dialog would let them name the field, associate a picture with it and add the feed URL.

How much effort would that be?

You wrote: Normally they are ordered by latest post first, and don't show all posts.

Does that mean the page content is generated dynamically from the RSS URL when the user clicks on the RSS widget?

**Comment by gilbert** [comment]
That adds some complexity. It might take up to 7 hours total. Do you think users will need to add multiple feeds? Most sites just have a blog post feed.

> Does that mean the page content is generated dynamically from the RSS URL when the user clicks on the RSS widget?

Yes, that is correct.

**Comment by onaseef** [comment]
I don't know that they will add multiple feeds. The customer asking about this is a guy who builds websites for cities, so I could see that he might want to be able to pull in multiple feeds. And blogger type people might want to do it as well. I figure it makes sense to plan for more flexibility rather than less.

**Comment by gilbert** [comment]
Practically every blog only has a single feed. If a website needs more, they can add multiple RSS widgets. Of course, asking users is always the best way to research.

**Comment by onaseef** [comment]
I'll talk to the user tomorrow. I don't like the idea of cluttering the home page with multiple feeds when it is better for visitors to have them grouped together.

We can always make it to where if there is only one RSS feed in the RSS widget, we just show the pages without making the user click a second time.

**Comment by gilbert** [comment]
Ok. For the record, the mobile visitor has no idea it's a feed. It's just a different widget in the same way that collection widgets are different from each other.

**Comment by onaseef** [comment]
How much work would it be to add an RSS feed to an existing Category?  So at the top level, we'd have an RSS feed widget which displays 1 RSS feed, and in a category, we'd add an "Add RSS" button. When the user clicks on it, it pops up a dialog where they can add a picture, title and URL. If the user clicks on the item and selects "Edit", it takes them to the RSS feed editor, which would just be a chance for them to change the RSS picture, title and photo. It would basically be the same contents as the dialog, but embedded in the Widget Editor sections.  

So the 2 items I'd like for this feature are:
1. RSS widget at the top level
2. Adding an RSS feed to a Category widget with the specs above.

**Comment by gilbert** [comment]
1. 4 hours, same estimate as mentioned above.
2. 4 hours, assuming 1 is done. By itself 2 would take 6 hours.

**Comment by onaseef** [comment]
What's the cost estimate? Am I getting any discounts? When would you be available to do this?

**Comment by gilbert** [comment]
Same rate. Discounts aren't really applicable since I won't charge over total estimates, and if I'm under then you pay less anyway. I'm available to do this starting tomorrow.

**Comment by onaseef** [comment]
You can go ahead and do 1 and 2

**Comment by gilbert** [comment]
I'm testing with random rss feeds, but do you have a specific feed from one of your customers you'd like me to test with?

**Comment by onaseef** [comment]
The customer's focus was on building mobile sites for cities so he was looking at directories, latest news, etc. Here's one of his sample sites: http://sanantonio.mymobilebuilder.com/app/movies/311830/6/rss.php

Try some from here. Try to get a broad swath of them. 

http://sanantonio.citysearch.com/rss_feeds
http://houston.citysearch.com/rss/lists.xml
http://www.kclibrary.org/blog/Keyword:%20Kids/feed

**Comment by gilbert** [comment]
The standalone rss widget is now available to test on branch `rss`

**Comment by onaseef** [comment]
I tested it out. The formatting looks good but it's not parsing correctly.  Check out this feed: http://www.fandango.com/rss/moviesnearme_78701.rss.  

There should be 19 items, yet only 4 are displayed on the page.

**Comment by gilbert** [comment]
It seems that an item count is required, and the default is 4. I'll make the default 10 and make it configurable in the builder.

**Comment by onaseef** [comment]
You mean as a drop down choice below the RSS link field?  If we're going to put a field, it should be a drop down so people don't put in garbage like -1 or 3x

**Comment by gilbert** [comment]
Sure

**Comment by onaseef** [comment]
So I added the RSS feed for: http://www.fandango.com/rss/moviesnearme_78701.rss.  I set the number to 25. 

Then I went through the feed by clicking the >> and << buttons and when I clicked on "Home" it didn't take me home.  The Category < (back) arrow also stops working.
