### ISSUE TITLE
Create a new site by copying an existing site

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#195]
This idea was inspired by talking to a guy who builds websites for cities. What he does is he creates a template site, and then duplicates that site over and over again, just changing the fields as he goes. A lot of what is on his site is RSS feeds, so he just updates those, but keeps everything else the same.

Can we create sites by copying an existing site, so the icons, names, order, etc are all the same, and then you go in and change the fields as necessary?

What would the scope of this be?

**Comment by gilbert** [comment]
This doesn't seem that hard, only 2 hours for the backend work. What sort of ui are you thinking of?

**Comment by onaseef** [comment]
The UI would be another button at the bottom with the text "Duplicate Site".  It would pop up the same dialog as the New Site button. The difference is that instead of the backend using the default template, it clones the public database content and uses that. So it has the same icons and content as the site it is a copy of.

**Comment by gilbert** [comment]
This would take up to 3 hours total.

**Comment by onaseef** [comment]
Please go ahead and implement this feature.

**Comment by gilbert** [comment]
This is available to test on branch `replicate`. I put the copy site ui into the "new site" dialog because it was less work. If you don't like it just let me know and I'll create a new dialog instead.

**Comment by onaseef** [comment]
I tried to run this and got the following error in the browser when I signed in:

LoadError in SessionsController#create

no such file to load -- couch
Rails.root: /Users/Omar/yomobi

Application Trace | Framework Trace | Full Trace
app/models/company.rb:3:in `<class:Company>'
app/models/company.rb:1:in`<top (required)>'
app/models/user.rb:34:in `company'
app/controllers/application_controller.rb:49:in`after_sign_in_path_for'
This error occurred while loading the following files:
   couch
Request

Parameters:

{"utf8"=>"âœ“",
 "authenticity_token"=>"fhYQqEzLCdIwvDjjlkq4pT70twjysuow4zPFC0ga+2Y=",
 "user"=>{"email"=>"lt@mail.com",
 "password"=>"[FILTERED]"}}

**Comment by gilbert** [comment]
Oops, try again now.

**Comment by onaseef** [comment]
Tried to do this, and here's the message:  (see InternalServerError)

Creating company with company_type_id: #CompanyType:0x007f879cf48320

Started POST "/sites" for 127.0.0.1 at 2012-03-19 15:22:42 -0500
  Processing by SiteManagerController#create as 
  Parameters: {"site"=>{"title"=>"ConnectHim", "url"=>"connecthim", "type"=>"57", "source_db_name"=>"ymtest"}}
  User Load (1.2ms)  SELECT "users".\* FROM "users" WHERE "users"."id" = 1 LIMIT 1
  CompanyType Load (0.2ms)  SELECT "company_types".\* FROM "company_types" WHERE "company_types"."id" = 57 LIMIT 1
  SQL (0.2ms)  SELECT COUNT(*) FROM "companies" WHERE ("companies".user_id = 1)
Completed 500 Internal Server Error in 3203ms

RestClient::InternalServerError (500 Internal Server Error):
  app/models/company.rb:48:in `create_couch'
  app/controllers/site_manager_controller.rb:45:in`create'

Rendered /usr/local/Cellar/ruby/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-3.0.8/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.6ms)
Rendered /usr/local/Cellar/ruby/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-3.0.8/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (5.8ms)
Rendered /usr/local/Cellar/ruby/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-3.0.8/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (13.5ms)

**Comment by gilbert** [comment]
Huh, that's strange. It's working for me. Can you pull my update and try again? I just added a debug message.

**Comment by onaseef** [comment]
Please update the UI in the New Site Dialog to have 2 radio buttons:
1. Create New Site: Dropdown list of site type  [Default]
2. Copy Existing Site: Dropdown list of sites to copy.

Remove the [Select a site to copy] and just make the first site in the list the first selected site.

**Comment by onaseef** [comment]
Here's the latest error message.  Also, it reserves the URL even though the site is not created.  That's not a good thing. If the creation fails, the URL should not be reserved.

Started POST "/sites" for 127.0.0.1 at 2012-03-19 15:51:46 -0500
  Processing by SiteManagerController#create as 
  Parameters: {"site"=>{"title"=>"connecthim", "url"=>"connecthim3", "type"=>"57", "source_db_name"=>"ymtest"}}
  User Load (1.1ms)  SELECT "users".\* FROM "users" WHERE "users"."id" = 1 LIMIT 1
  CompanyType Load (0.3ms)  SELECT "company_types".\* FROM "company_types" WHERE "company_types"."id" = 57 LIMIT 1
  SQL (0.2ms)  SELECT COUNT(*) FROM "companies" WHERE ("companies".user_id = 1)
Completed 500 Internal Server Error in 2523ms

RestClient::InternalServerError (500 Internal Server Error):
  app/models/company.rb:49:in `create_couch'
  app/controllers/site_manager_controller.rb:45:in`create'

**Comment by gilbert** [comment]
There should be a message that says `Replicating existing couch: ...` somewhere. Can you copy/paste it here?

**Comment by onaseef** [comment]
Also, when it fails, it deletes the Site Name the user put into the site name field.  No reason to delete this field on fail.

Here's the error message you asked for:

Creating company with company_type_id: #CompanyType:0x007fd42f724da8
Replicating existing couch: http://yadmin:C0uch!tUp@yomobi.iriscouch.com/m_ymtest

Started POST "/sites" for 127.0.0.1 at 2012-03-19 16:16:22 -0500
  Processing by SiteManagerController#create as 
  Parameters: {"site"=>{"title"=>"connecthim", "url"=>"connecthim6", "type"=>"57", "source_db_name"=>"ymtest"}}
  User Load (1.2ms)  SELECT "users".\* FROM "users" WHERE "users"."id" = 1 LIMIT 1
  CompanyType Load (0.3ms)  SELECT "company_types".\* FROM "company_types" WHERE "company_types"."id" = 57 LIMIT 1
  SQL (0.2ms)  SELECT COUNT(*) FROM "companies" WHERE ("companies".user_id = 1)
Completed 500 Internal Server Error in 2854ms

RestClient::InternalServerError (500 Internal Server Error):
  app/models/company.rb:49:in `create_couch'
  app/controllers/site_manager_controller.rb:45:in`create'

Rendered /usr/local/Cellar/ruby/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-3.0.8/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.9ms)
Rendered /usr/local/Cellar/ruby/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-3.0.8/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (6.6ms)
Rendered /usr/local/Cellar/ruby/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-3.0.8/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (17.0ms)
