### ISSUE TITLE
PRODUCTION BUG: Call Us widget pops up error dialog 

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#197]
When you browse to a yomobi website on a desktop and you click on the Call Us widget, it pops up an error dialog saying "tel" isn't supported. The problem looks especially bad on Safari on the Mac. When I click on the Call Us button of any yomobi site, eg: shandeez.yomobi.com, the whole browser takes me to an error page. When I click "back", it takes me to the phone page.

Since we can tell when a user is browsing from a mobile device or not, we need to modify the mobile display code to bypass the tel link altogether when the user is not mobile.

This is a big problem because we're telling people that they can bypass a desktop site altogether and go straight to mobile, which means the way our site displays on a desktop should be smooth.

**Comment by gilbert** [comment]
Would it be acceptable to disable this in preview mode, since the mobile site is only really viewed on mobile devices where this problem doesn't exist? The mobile detection is another bit of load that will slow down the mobile page load.

**Comment by onaseef** [comment]
Preview mode isn't the issue. One of the messages we have is that people can skip building a desktop site and just use a mobile site for all their customers, even those on a desktop. So our mobile sites need to work well as desktop sites too.   I definitely don't want to slow down the load of a mobile page though.  Are their other options?

**Comment by gilbert** [comment]
It won't be a significant amount, just something to keep in mind as we add more stuff. I'll just add it in.
