### ISSUE TITLE
Remove the [? picture] if the user doesn't upload a photo or deletes their existing profile photo

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#203]
Apparently many small businesses may not have a profile picture, so we'd like to make it where if they don't upload a photo, we just leave the header bar with just the title and no place-holder for the picture. If they upload a picture, we'd show it. If they delete it, the header goes back to being just the title with no picture placeholder.

**Comment by gilbert** [comment]
This was easy enough that I just went ahead and did it.
