### ISSUE TITLE
Add 4th step to wizard

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#207]
This page is the "reward" page that says: congratulations, your site is online, here's the link, here's how to market it. etc

**Comment by gilbert** [comment]
This is available to test & fill in on branch `step-4`. The new file to edit is called `step-4.slim`.

**Comment by onaseef** [comment]
"Skip this Step" link on 3rd page goes directly to the builder, bypassing the 4th page. It should take the user to the 4th page.

**Comment by gilbert** [comment]
Fixed.
