### ISSUE TITLE
Add a text field to the "Call Me Back", "Leave a Message", "Keep Me Informed" widgets so the user can put their own message

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#215]
In the editor for the: Call Me Back, Leave a Message and Keep Me Informed, we need to add a multi-line text field where the user can type in their own message for the mobile viewer to see.

**Comment by gilbert** [comment]
This would take up to an hour.

**Comment by gilbert** [comment]
This is available to test on branch `wtest`

**Comment by onaseef** [comment]
The default message we now have for each form should appear in the text field initially and on the mobile site unless the user explicitly overwrites it with a message they've entered in the text box. 

Whatever text is entered in the text field should be trimmed before and after of white spaces.
If the user blanks out the field, on save, it should revert to the default message.
If all that is in the field is white space, it should be treated as if it is empty and revert to the default message on save.

Since we're doing I18N now, the default message that appears should not pulled from wherever we set it now.

Add the help ? icon with help text next to the labels for the next text fields.

**Comment by gilbert** [comment]
Ok, updated.

**Comment by onaseef** [comment]
Please don't forget the trimming of before and after white space upon save and the ? icon with help text.

**Comment by gilbert** [comment]
All right, all string values are now trimmed on save. Help bubbles are there too.
