### ISSUE TITLE
Replicate Error: Can't edit the site

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#219]
Testing locally on my machine and connecting to database ymtest, I get the following error when I try to edit the site:

Uncaught TypeError: undefined is not a function

  newWidget: function (data) {
    return new window.widgetClasses[data.wtype](data);
  },

The javascript console reads:

2event.layerX and event.layerY are broken and deprecated in WebKit. They will be removed from the engine in the near future.
util.js:464Got meta! 
Object
util.js:464app render
2event.layerX and event.layerY are broken and deprecated in WebKit. They will be removed from the engine in the near future.
util.js:464widget res 
Object
util.js:353Uncaught TypeError: undefined is not a function
68event.layerX and event.layerY are broken and deprecated in WebKit. They will be removed from the engine in the near future.

**Comment by gilbert** [comment]
I've gotten this error before too. It happens when you try to edit a site that contains an RSS widget when you're not on a branch that supports them.

I'll write a patch and apply it to master. You should be able to cleanly merge master into any branch that has this problem.

**Comment by gilbert** [comment]
Also, I'm sure you're already doing this, but when you switch to a branch that supports rss, you need to restart the server.

**Comment by gilbert** [comment]
Test comment.
