### ISSUE TITLE
home-redesign branch: Can't add category to site

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#222]
Now that the home-redesign has been merged, i can't add a category to the site, I'm guessing because it has an RSS option. I can add an RSS widget though.

I'm pointing to the ymtest database.  The javascript error I get when I try to add a category is:

Uncaught RangeError: Maximum call stack size exceeded
window.Widget.window.Widget.extend.validate

**Comment by gilbert** [comment]
Fixed.
