### ISSUE TITLE
home-redesign: Can't change icon on custom rss feed widget

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#227]
I add an RSS widget to my site and I try to change the icon and i get the following error:

Uncaught ReferenceError: google is not defined
window.widgetClasses.rss.Widget.extend.getShowDatarss.js:28
window.Widget.Backbone.Model.extend.getPageContentbase.js:23
util.widgetPage.refreshbase.js:190
window.EditWidgetView.Backbone.View.extend.refreshViewsedit-widget.js:131
_.bindunderscore.js:409
window.EditIconDialog.Backbone.View.extend.saveIconedit-widget.js:309
window.EditIconDialog.Backbone.View.extend.prompt.buttons.Saveedit-widget.js:295
(anonymous function)jquery-ui-1.8.17.custom.min.js:106
f.event.handlejquery-1.6.2.min.js:17
f.event.add.i.handle.k

**Comment by gilbert** [comment]
Fixed.
