### ISSUE TITLE
ymtest.yomobi.com fails because of RSS feed widget

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#230]
On the production server, because the RSS widget isn't known, ymtest.yomobi.com fails.  I haven't pushed the RSS code changes to production yet, so this was a random find.

I want to know how safe it is to push these changes to production and if there's a graceful way to handle this issue.

When I push the RSS widget changes to production from the home-redesign branch, do I need to do a db migrate?

**Comment by gilbert** [comment]
This should be fixed via #219. When was the last time you pushed to production?

**Comment by onaseef** [comment]
haven't pushed in a while. When the other issues are fixed I can do a push and see how it goes.

**Comment by gilbert** [comment]
The fix is on the master branch, so it won't include everything from home-redesign

**Comment by onaseef** [comment]
All changes need to be part of the home-redesign branch because that's the one that gets pushed to production and that's the one I'm treating as the primary branch.

**Comment by gilbert** [comment]
It's part of home-redsign too. I'm pretty sure you're the one who merged it in.
