### ISSUE TITLE
i18n: confirmation_instructions.html.erb

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#241]
What's the correct format for line 7. I dont' know how to use the =t' inside the <%= link_to... tag.
Would you please confirm in general that this is the right format?  I haven't saved it to the repository because it isn't working yet, so you'll have to look at it here.

1<p><%=t('confirm_account_email.greeting', :first_name => @resource.first_name) %></p>
2
3<p>=t'confirm_account_email.thank_you'</p>
4
5<p>
6=t'confirm_account_email.confirm_msg' 
7<%= link_to =t'confirm_account_email.click_to_confirm', confirmation_url(@resource, :confirmation_token => @resource.confirmation_token,:uid => @resource[:id]) %>
8</p>
9
10<p>=t'confirm_account_email.signature'</p>

**Comment by gilbert** [comment]
You probably need parenthesis for the `t` function:

```
<%= link_to =t('confirm_account_email.click_to_confirm'), confirmation_url(@resource, :confirmation_token => @resource.confirmation_token,:uid => @resource[:id]) %>
```

**Comment by onaseef** [comment]
fixed
