### ISSUE TITLE
deelmob: new account signup fails

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#246]
Using Windows, IE7, or firefox or chrome, go to www.deelmob.com and create a new account by clicking on Sign Up.  For the sake of conformity, please use un: ymtest7@mailinator.com pw: 123123 to create your new account.

After the first step of the wizard, it fails with the following message:

NoMethodError in SignupController#account_setup 
You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.[]
Rails.root: /app

**Comment by gilbert** [comment]
I just created an account on ie7 using that email/pass with no problems. Maybe it's not ie7 related?

**Comment by onaseef** [comment]
It turns out it is related to the locale.Try it again with www.deelmob.com?locale=es.  Then it will fail.

**Comment by gilbert** [comment]
Got it.
