### ISSUE TITLE
deelmob: Step 3 of the wizard, upload button doesn't enable in spanish

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#248]
Go to www.deelmob.com
Set locale=es

Sign up for a new account. To standardize things, please use ymtest11@mailinator.com pw: 123123

In step 3 of the wizard, after you select a picture, the spanish language "Upload" button doesn't enable. I theorize it's because the code that enables the button it is looking for the word "Upload" but since we internationalized, the value is different.

Just in case, I'm using IE 7 on windows.

**Comment by gilbert** [comment]
Ok, I'll get to this. In the future can you start posting these as comments in its related user story? Thanks. https://planscope.io/projects/yomobi/stories/3182
