### ISSUE TITLE
Deelmob: Site Manager fails as follows:

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#251]
Log in to deelmob.com and click on Site Manager and see the following:

LoadError in SiteManagerController#index

no such file to load -- SecureRandom
Rails.root: /app

Application Trace | Framework Trace | Full Trace
app/controllers/site_manager_controller.rb:4:in `<class:SiteManagerController>'
app/controllers/site_manager_controller.rb:1:in`<top (required)>'
This error occurred while loading the following files:
   SecureRandom
Request

Parameters:

None
Show session dump

Show env dump

Response

Headers:

None

**Comment by gilbert** [comment]
Fixed.
