### ISSUE TITLE
Customization: Banner Tweaks

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#254]
1. For the banner customization, make the banner image that appears in editor panel on the right a maximum width of 64px. The actual banner can be larger, but we don't need the full size image on the right.
2. Add a size field to the banner edit box so the user can customize the size of the banner image from 1-100% in case they want to make it bigger
3. Modify the CSS so the image is always horizontally centered.

**Comment by gilbert** [comment]
1. Updated
2. This would take an additional hour an a half
3. Updated

**Comment by onaseef** [comment]
Please go ahead and implement the size field for the banner edit box.

**Comment by gilbert** [comment]
Ok, I will get to this today.

**Comment by gilbert** [comment]
Updated.
