### ISSUE TITLE
Please validate the latest commit to master

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#255]
When you fixed the issue with the page size, I notice that you added the line:  _.delay(function() { mapp.resize() }, 100);  to the file: mobile-app.js.  But it was added to the customize rather than master branch, so I added it to the master branch while fixing another issue. 

Since this is a delay function, if it is not needed here, I'd rather remove it.  Please check the most recent push to master and verify whether the delay line is needed or not.

**Comment by onaseef** [comment]
Did you have a chance to look at this issue? Please comment on what needs to be done.

**Comment by gilbert** [comment]
Yes it is. It fixes the mobile resizing bug where it was cutting off the bottom part of the mobile site.

**Comment by gilbert** [comment]
The delay is not a "wait" function, it's a function that executes a function at a later time. It does not increase page load time.

**Comment by onaseef** [comment]
How did the change get pushed to production if it is in the customize branch rather than master?

**Comment by gilbert** [comment]
I don't remember.
