### ISSUE TITLE
Premium branch: Custom Domain buttons not working

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#258]
In the premium branch, even for an upgraded custom site, the Add Domain / Remove Domain buttons remain disabled.

**Comment by gilbert** [comment]
What browser is this happening in?

**Comment by onaseef** [comment]
In my case, all of them.

**Comment by gilbert** [comment]
Oh that's right, they're disabled unless you are the site owner.

**Comment by onaseef** [comment]
This feature should be enabled for any person with administrative rights.

**Comment by gilbert** [comment]
Updated.
