### ISSUE TITLE
premium: custom domain notes and reminders

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#259]
1. The design of the custom domain feature should be such that if we need to disassociate a custom domain from a particular mobile site, we can do so easily, and also easily assign the domain to a new site if necessary. 
2. As a reminder, with the custom domain feature, if a user types in a domain that already is in use, they should see a message box that says: This domain is already in use. If this domain is yours, please enter your contact email address and click "Send Email" to notify us and we will investigate. "

**Comment by gilbert** [comment]
1. Is this requirement fulfilled?
2. A mailto: anchor would be sufficient. You can add it in `site_manager.error.domain_taken` (line 680 of en.yml at time of writing)

**Comment by onaseef** [comment]
This requirement will be fulfilled if: 
1. there is an easy way to query _by domain_ to determine which mobile site is associated with that domain. 
2. There is is an easy way to disassociate a domain from a particular mobile site.
3. There is an easy way to assign a domain to a mobile site.

Is there a mechanism in place that allows us to do that?

**Comment by gilbert** [comment]
I just added domains to the admin panel. You can search by domain too.
