### ISSUE TITLE
master: add links that allow user to select their preferred language

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#260]
Part of the initial requirement for the i18n work was to have links on the home page where users can select their preferred language. I'm thinking a nicely integrated dropdown list like what on twitter.com that pops up a menu where the user can select their preferred language. It can be placed below the yomobi logo on the home page.

**Comment by gilbert** [comment]
I remember you saying to make them like facebook, so that's what I did since it was the easiest way to do it.

**Comment by onaseef** [comment]
Which branch is this on?

**Comment by onaseef** [comment]
Why are your changes saving to the premium branch, instead of master?

**Comment by gilbert** [comment]
My understanding is that premium has become the new development branch, and master is the production branch.

**Comment by onaseef** [comment]
For incremental changes of this nature or bug fixes, they would go into the master branch, because I would push out those changes before pushing out all the major changes in premium. Is there a way to merge a specific change from premium into master without getting the rest of the changes that exist in premium?

The ideal scenario I'd like is that I'd like to mark a point in master as stable so that I can always push out that specific point if pushing out a later point breaks something. Is there a git push command to do that? Or, what is the sequence of steps to accomplish that goal?

**Comment by gilbert** [comment]
If you go to the history tab in the github app, on the right side of each commit you'll see a random string of letters and numbers below a date. This is the commit id (you can see the longer version by double clicking the commit).

Copy the commit id (short or long) to your clipboard, then switch to the branch you want to copy it to. Then, in the command line, run the command:

```
$ git cherry-pick abc123
```

where `abc123` is the commit id. If there's a conflict, you'll have to run `git mergetool` to resolve it.
