### ISSUE TITLE
Premium branch: Site failure when trying to do a recurring monthly payment

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#265]
Log in to deelmob.com as aatest25@mailinator.com 123123. Go to the site manger and select recurring monthly payment. You can use this link for the CC input info: https://www.wepay.com/developer/reference/testing

After you try to validate, it takes you to local.host:3000 as at the URL, so than I changed that to www.deelmob.com/<etc> and I get the error:

ActiveRecord::UnknownAttributeError in Wepay::CheckoutController#index

unknown attribute: manage_uri
Rails.root: /app

Application Trace | Framework Trace | Full Trace
Request

Parameters:

{"security_token"=>"28381b3aad7c574a45253e1e530a8556898d8ecee7e727cf7275a0609d0ce058",
 "preapproval_id"=>"153997"}
Show session dump

Show env dump

Response

Headers:

None

**Comment by gilbert** [comment]
Fixed.
