### ISSUE TITLE
Premium branch: Banner image size should reset to "original" if a new image is uploaded

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#266]
If I upload one image to the Banner and set the size to be anything other than original, and then upload another banner image, even though the system puts it at "original" size, the banner dropdown stays at whatever i had it at last instead of adjusting to original.

**Comment by gilbert** [comment]
Fixed.

**Comment by onaseef** [comment]
Now it defaults to 20% when you upload an image, instead of defaulting original. You can see it when you log in to www.deelmob.com as aatest25@mailinator.com 123123

**Comment by onaseef** [comment]
I need to test this more to see exactly how to reproduce it. But it did happen.
