### ISSUE TITLE
Cancel Subscription must be done twice

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#271]
Log in to www.deelmob.com as aatest25@mailinator.com 12123

Do a recurring payment.  You can use CC # 4003830171874018  and whatever else you want for the rest of the data

Once you've made the payment, click on cancel subscription.  After you cancel it, and go somewhere else and come back to the site manager and look at the account type, you see the subscription is still in place till you cancel it again.

**Comment by gilbert** [comment]
Fixed.
