### ISSUE TITLE
Removing domain hangs

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#272]
deelmob.com aatest25@mailinator.com 123123

There were 4 domains associated with the site, I tried to remove all of them and when it came to the last one www.cnn.com, it doesn't work.

**Comment by gilbert** [comment]
Ah ok, so the cnn domain is causing problems. Was a similar, big profile domain causing problems too in #273? I think it may be that these domains are already in use by another heroku app, and thus throwing errors when our app is trying to add/remove them.

**Comment by onaseef** [comment]
Is the issue that we aren't handling errors correctly? Is there a more robust error handling mechanism?

**Comment by gilbert** [comment]
Of course, I just want to know if the domains are the underlying cause.

**Comment by gilbert** [comment]
Fixed.
