### ISSUE TITLE
UI Tweaks for Payment Process

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#278]
1. Instead of jumping to the payment history page upon success, show a success message and stay on the current view. 
2. If the "I agree to terms" isn't checked, catch that before doing any other processing. Right now, it seems to do something else before check if "I agree" has been selected. 
3. Since it takes a while to process the Submit, disable the button until a response comes back, than re-enable
4. After the user clicks "Confirm Payment" it takes a while to process. We should disable the Back button and add a "Processing" message next to it for user feedback. When we get feedback, we should reenable the "Back" button and remove the "Processing" message.

**Comment by gilbert** [comment]
Updated.

You can't disable the back button in a browser, but you can confirm leaving the page, of which I added.

Since it's an iframe, it's not possible to detect when the "Confirm Payment" button is clicked.

**Comment by onaseef** [comment]
The "Confirm Leaving" dialog appears 3 times when I click the Submit button in the WePay iFrame. This should be removed. I'd rather go back to the way it was before where you hit Confirm Payment and than wait.

Here's the flow I'd like. Please tell me if there are any technical barriers to this UI flow.
1. User presses "Confirm Payment"
2. In the same space as the iFrame, UI shows a message saying: "Your payment is being processed, please wait." with some sort of animated action icon.
3. After the back end processing happens, in the same space as the iFrame, the UI shows the status. 
4. If the payment is successful, it shows a status message like: "Your payment was accepted. You now have a Custom site." There should be a "View Payment History", "Edit Site", and "Close" buttons
5. If the payment fails it shows a status message indicating why it failed and a "Start Over" and "Close" button.

**Comment by gilbert** [comment]
It's not possible to detect any events inside an iframe due to browser security. Basically we can't change the wepay ui at all.

**Comment by onaseef** [comment]
How close can we get to the UI I've suggested? For sure, we need to remove the "Confirm Leave" dialog because it doesn't flow well.

How do you know when the payment has been successful or has failed? Can we use that callback as a trigger to update the user without switching to a different view? What I have in mind is that when we get the callback from WePay, we'd hide their iFrame and show our status update.

Also, how do you deal with recurring payments? How does WePay notify us when a new recurring payment has come in? Is it something automatic, like you have a listener that waits from updates from WePay and updates the end date of a custom account?

**Comment by gilbert** [comment]
The "Confirm Leave" is only supposed to appear once. Although I can fix it, I just realized that once the iframe is done processing, the page redirects, causing the confirm to appear even though the processing is complete.

There is a success message, of which I just fixed a bug relating to it.

WePay hits a specific url on our app server for changes and updates, where it updates records accordingly.
