### ISSUE TITLE
IE 9/8: Advanced Customization - Edit Panel Bug

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#279]
On Windows 7 with IE9 and possibly IE8, if you click on Advanced Customization and then click on the "Header", "Tab Bar" dropdown (or anywhere in the edit panel for that matter), it brings up the file browser. The rest of the controls don't respond.

To duplicate: www.deelmob.com aatest24@mailinator.com 123123 
Click on Site Manager and then click back on Website Builder, then click on Advanced Customization. Now, clicking anywhere on the builder brings up the file browser.

**Comment by gilbert** [comment]
Fixed

**Comment by onaseef** [comment]
This is still happening on IE9

**Comment by gilbert** [comment]
Sorry about that, I found the real cause this time.
