### ISSUE TITLE
IE 9/8: Advanced Customization - Banner Image Upload Bug

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#281]
deelmob.com / aatest24@mailinator.com / 123123

IE8/9 on Windows 7

Click on Advanced Customization and load a new banner image. The file uploader progress bar doesn't show progress, and when it's done, it stays stuck at 100%.  

See image: http://ge.tt/9M2jG6I

**Comment by gilbert** [comment]
Fixed. For whatever reason, flash is not reporting the file progress.
