### ISSUE TITLE
All Browsers: bug when clicking on "Submit" in Site Grade  

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#287]
On Windows on IE8 & Chrome, etc

www.deelmob.com aatest25@mailinator.com 123123

Go to site manager, click on Site Grade and Select One Year and withOUT clicking on "I agree to terms", click on "Submit".

First you get a dialog with the text "bad". Then when you click ok, you see the "please agree to terms" dialog, then when you click OK see the error message flashing: "undefined: agree_to_terms".  It hasn't been I18N-ized

**Comment by gilbert** [comment]
Fixed. I can't seem to prevent the form from submitting in ie. If you want I can skip the "please agree to terms" dilago in ie so it won't show two error messages at once.

**Comment by onaseef** [comment]
I'd rather keep the error dialog.  So long as the error message is i18n enabled, it's fine to have both in IE

**Comment by gilbert** [comment]
Ok. The message is in `en.yml:136`
