### ISSUE TITLE
IE8: Customization Error - Panel doesn't appear.

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#288]
I was in Site Manager, than I clicked on Website Builder than Advanced Customization and nothing showed up in the panel. I checked the browsers error messages, which you can see here: http://ge.tt/7e9jSEI

If you click on the dropdown, it all starts working again.

**Comment by gilbert** [comment]
It seems to be working on my ie7 and ie9. Somehow my ie8 got upgraded to 9. I'm downloading a vm for 8 right now and will see if I can reproduce it there.

**Comment by gilbert** [comment]
I couldn't get ie8 installed on the windows machine. The downloads from microsoft.com were always "corrupt" somehow. Is this issue by chance fixed by the latest updates?

**Comment by onaseef** [comment]
I did test it and so far it seems to work.
