### ISSUE TITLE
Advanced Customization & other sidebar links fail

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#289]
deelmob.com aatest25@mailinator.com 123123

Click on Advanced Customization in the left hand navigation panel. Make no changes
Click on any widget that is already on the site. 
Notice that the URL hasn't changed from: http://www.deelmob.com/builder/main#customize
Click on Advanced Customization again the left hand navigation panel

Nothing happens.

The same thing happens with the other sidebar links if you click on them to edit than click on a widget to edit. Because the URL doesn't update, when you click on it again, nothing happens.

**Comment by gilbert** [comment]
Fixed.
