### ISSUE TITLE
On Android phone, mobile site doesn't handle advertisement properly

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#290]
On an android phone, if you go to ivescuts.yomobi.com, you'll see an add from Progressive Insurance. Something about this ad makes the rest of the mobile site not work. It's as if it is capturing all of the clicks because the Z-index or something of that nature. This has been going on for months. I've tried to get around it by blocking progressive ads, but it still keeps coming back, so we need to find a fix.

Are we handling the ad bar space properly?  Is the z-index right?  I'm stumped.

**Comment by gilbert** [comment]
I don't have an android phone to test with, but the z-index shouldn't be an issue. It sounds like the ad is misbehaving and jumping outside its container. I would contact the ad service and report that specific ad.

**Comment by onaseef** [comment]
The ad is jumping outside the container. The question is, can we constrain it to keep it from doing that?

**Comment by gilbert** [comment]
I can try putting an `overflow: hidden` on the ad bar, but other than that not really.
