### ISSUE TITLE
i18n: The site manager code needs to be internationalized

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#293]
It looks like a lot of the values in the site_manager_controller.rb need to be internationalized.

**Comment by gilbert** [comment]
I only see lines 223 and 224 than need it. Am I missing some?

**Comment by onaseef** [comment]
There's also 216, 217, 218 which factor into 223 and 224.

**Comment by onaseef** [comment]
I also was looking at: Select a Thing, the radio button labels, I agree to terms, Submit, and any error and success messages.

**Comment by gilbert** [comment]
Oh ok, I'll handle the controller ones. I was going to wait for the final ui before doing the front end i18n.

**Comment by onaseef** [comment]
It makes sens to wait on the front end until the final UI is complete.
