### ISSUE TITLE
ie8: javascript error when trying to upgrade an account

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#295]
deelmob.com aatest24@mailinator.com 123123

I go to site manager and click on site grade and selected monthly subscription and when I click on Submit, I see "Error on Page" i the browser bar.  

See http://ge.tt/889eoMI

**Comment by gilbert** [comment]
Fixed.

**Comment by onaseef** [comment]
There's another javascript now when doing the same thing  

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET4.0C; InfoPath.3; BRI/2; BOIE8;ENUS)
Timestamp: Wed, 30 May 2012 00:38:48 UTC

Message: Object doesn't support this property or method
Line: 8
Char: 801
Code: 0
URI: https://stage.wepay.com/min/js/v20120529173620._shared.taxes-_shared.address-flow.js

**Comment by gilbert** [comment]
I get that error too. It's in WePay's javascript code. Can't do much about it.

**Comment by onaseef** [comment]
Does it impact the functionality in any way that you're aware of?

**Comment by gilbert** [comment]
It doesn't seem to.
