### ISSUE TITLE
Account Settings: Make UI fit the links on the left

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#298]
We can use the same form, however, when the user clicks on "Change Account Information" we should hide the Password section and when they click on "Change Password", we should hide the account information section and make the Password fields required.

**Comment by gilbert** [comment]
Updated.

**Comment by onaseef** [comment]
Click on Change password, than without entering anything, click no "Save Changes". Notice how the form reverts to the Change Account Information view.

**Comment by gilbert** [comment]
Fixed.

**Comment by onaseef** [comment]
From doesn't check for empty new passwords. If the password is empty, it doesn't give an error message, it just says "Account Updated Successfully". The good news is that it doesn't actually set a blank account, but we should say: "New password cannot be empty".

**Comment by gilbert** [comment]
Oh that's right. The "optional new password" aspect was still there from the original form. Fixed.
