### ISSUE TITLE
Site doesn't handle transition from premium account back to standard

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#299]
www.deelmob.com aatest24@mailinator.com 123123

I changed the account from premium to standard to test out what the interface does with the custom css.  If you go into advanced customization, it pulls the values from the custom css and then when you leave, it asks if you want to save or cancel and if you hit cancel, it updates the emulator css with the custom css changes, rather than ignoring them altogether.

To reproduce, log in with the credentials above.  Notice how the emulator starts off with the standard colors.
Click on Advanced Customization, chance the header font to anything. Click on a widget to edit it. When the: do you want to discard changes dialog appears, click "OK". Notice how the emulator updates.

**Comment by gilbert** [comment]
Fixed.
