### ISSUE TITLE
Site status notification message wrong for annual subscription

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#300]
If you select the annual subscription, in the site manager, after payment, it shows the status as monthly subscription even though it's an annual subscription.

I figure the easier thing to do is change the text to: 

Subscription Type: monthly / annual; Expiration: Date;    Renew  -  Cancel  

With "Renew" it can just bring up the existing payment options we have.

**Comment by gilbert** [comment]
Fixed. The renew feature is specified in #301.
