### ISSUE TITLE
Need option to renew a subscription

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#301]
If the user is on a subscription model, there's no way for them to renew the subscription, they can only cancel the subscription. We need a way to renew the subscription so that it doesn't first have to expire before it can be renewed.

**Comment by gilbert** [comment]
WePay doesn't let you modify a subscription, so the user will have to re-enter their cc info.

**Comment by onaseef** [comment]
That's fine. They can go through the process again and select from the options available. We just need a way to allow them to continue the premium account without it having to expire first.

**Comment by gilbert** [comment]
Option added. If there's a previous subscription, it cancels it in favor of the new one (only if the new one is a subscription too).

**Comment by onaseef** [comment]
Do you have to cancel the previous subscription? Can the new one be set to start at the end of the existing one and continue from there?  Better yet, does WePay have the concept of just extending the end date of the existing subscription?

**Comment by gilbert** [comment]
WePay does not give the option to extend a subscription. There's only create and cancel. It does look like I can start the subscription at a later date, though.

**Comment by onaseef** [comment]
Since WePay can start the subscription at a later date, we should start it one day before the end of the last payment cycle that was made.
