### ISSUE TITLE
Javascript substring error on About Us page when trying to save

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#304]
deelmob.com aatest24@mailinator.com 123123

See: http://ge.tt/5yxTYSI/v/0?c

Select site aatest26.  Notice that the About Us page has the exclamation icon indicating it won't appear on the site.

Click on the About Us icon to edit, and just hit Save Changes on the widget and you get the following error:

---

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET4.0C; InfoPath.3; BRI/2; BOIE8;ENUS)
Timestamp: Thu, 31 May 2012 13:58:25 UTC

Message: 'substring' is null or not an object
Line: 65
Char: 9
Code: 0
URI: http://www.deelmob.com/javascripts/widgets/builder/base.js?1338411595

**Comment by gilbert** [comment]
Fixed.
