### ISSUE TITLE
Add WePay iFrame customization parameters

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#307]
https://www.wepay.com/developer/tutorial/customization

Please add the customize color parameters to the iFrame call. The current "Continue" button looks disabled because it's gray so I want to change it to green. If you add the parameters, I can customize the colors on my own.

**Comment by gilbert** [comment]
This isn't part of the iframe call.

Try this. First run this once:

```
$ gem install restclient
```

Now put this in a new file called `wepay_customize.rb` (or something similar), filling in the necessary info:

``` ruby

require 'restclient'
require 'json'

theme_object = {
  "primary_color" => "FFFFFF",
  "secondary_color" => "000000",
  "background_color" =>"004C64",
  "button_color" => "0084A0"
}

params = {
  :client_id => 'WEPAY_CLIENT_ID',
  :client_secret => 'WEPAY_CLIENT_SECRET',
  :theme_object => theme_object
}

response = RestClient.post 'http://stage.wepayapi.com/v2/app/modify', params.to_json
puts response.inspect
```

Now run the file:

```
$ ruby wepay_customize.rb
```

This will post data to WePay's servers and change your app's settings.

**Comment by gilbert** [comment]
I added a file called `wepay.rb`. You can edit the hex values in this file, then update it by running:

```
$ ruby wepay.rb
```
