### ISSUE TITLE
Update mobile render to include ad bar in all cases except for premium sites

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#310]
Now that we have the paid custom site, we want to encourage users to upgrade to the custom site, so i'd like to put the ad space back in on both the mobile emulator in the builder and in the preview mobile site.

In both the mobile emulator and preview mobile site views, the ad space only appears if the site is not a premium site.  It will be 50px in height at both the top and the bottom. It will be a text space that says: "Upgrade to a custom site to remove this ad". When when the user clicks on the space, it takes them to a help URL that explains what to do.

**Comment by gilbert** [comment]
Added. The ad content is in `_yomobi-upgrade-ad.html.erb`, and the styling is in `mobile.scss`.

**Comment by onaseef** [comment]
1. The upgrade ad bar should appear at the bottom as well. 
2. The preview mobile site height is not being calculated properly, the footer is being cut off.
