### ISSUE TITLE
Site Grade message doesn't update 

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#313]
www.deelmob.com aatest25@mailinator.com 123123

I selected the site aatest24copy and I chose the AutoPay Yearly.  When I successfully pay, the status message shows:

Custom (next charge: 2013-07-05) 

When I cancel the subscription, I see the message that the subscription cancelled successful, however the status message is still: 

Custom (next charge: 2013-07-05)

It doesn't updated until I leave Site Manager altogether and come back. It should update so people won't be concerned about there being a next payment.

**Comment by gilbert** [comment]
Updated.
