### ISSUE TITLE
IE8/9? Advanced Customization Javascript Error

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#314]
http://www.deelmob.com  aatest24@mailinator.com 123123

Go to site manager and edit site aatest24copy if it is not already selected. 

Go to Advanced Customization.  There's a javascript error which causes various problems.   

See: http://ge.tt/2OfdelI/v/0?c  (there are 2 images at this link. hover over the image and use the arrows that appear to navigate between them)
1.  When I get to the Advanced Customization panel, the edit panel is missing
2. If I use the drop down select to pick something else, the edit panel appears, but the color selector doesn't work.

**Comment by gilbert** [comment]
I still can't seem to reproduce this error, though I do have a guess on why it's happening. Can you try it now?

**Comment by onaseef** [comment]
Haven't seen this happen recently either.
