### ISSUE TITLE
WePay Error: Payment feature stopped working

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#315]
www.deelmob.com aatest24@mailinator.com 123123

When I go to upgrade a site and I click "I agree" and Submit, nothing happens.  When I look at the JS error, it tells me: WePay is not defined.

**Comment by gilbert** [comment]
Have payments ever worked on staging? I haven't set up the environment for it to work anywhere but local.

The iframe should still pop up though. I just tried using that login and it worked. That specific js error is on WePay's side (there's no "WePay" variable in our code).

**Comment by onaseef** [comment]
The payments do work on staging. That's where I've been testing it all along. After you make a payment you have to manually set the URL back to www.deelmob.com.

The frame is showing up again. I don't know what the issue was.
