### ISSUE TITLE
Site Manager: Keep expanded element of accordian open when selecting different sites in the list on the left

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#317]
In the site manager, if I expand the Site Admins section and then select a different site from the list on the left, the Site Admins section stays expanded while getting updated.  With any other section, if I select a new site from the list on the left, it collapses. Can we make whichever section is expanded stay expanded even as we select different elements in the list.

**Comment by gilbert** [comment]
Added.

**Comment by onaseef** [comment]
When you click on a header the code add the "active" attribute to it. With the new changes, the header loses its "active" attribute when you switch between sites, which impacts the CSS. Right now, only the last element header keeps its active state. The rest should  maintain it as well.

**Comment by gilbert** [comment]
Fixed.
