### ISSUE TITLE
Customization Bug

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#318]
www.deelmob.com aatest24@mailinator.com 123123

go to account settings and select aatest24copy to edit

Click on advanced customization, and select Mobile Tab Bar & Footer and set the text color to something different than it is

Save Changes

click on the tab bar in the emulator to edit the tabs

Change one of the tabs.

Notice that once it updates, the tab text color changes back to what it was.

**Comment by gilbert** [comment]
Fixed
