### ISSUE TITLE
WePay unkown_error message when trying to pay

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#319]
www.deelmob.com aatest25@mailinator.com 123123

See: http://ge.tt/3rfzuoI/v/0?c

Go to site manager and expand the site grade section and select the middle site and try to do a recurring monthly payment and you get the message "Error: unknown_error".

You may have to select the other 2 sites and play around with it a bit go reproduce it, because sometimes it worked and other times it failed over and over.
1. Why are we getting this error?
2. The message "unknown_error" should be i18n and hopefully provide some useful information if there is useful information to provide.

**Comment by gilbert** [comment]
Updated. The error was due to the start charge time being in the past. I added a 3 hour cushion to fix this. This doesn't affect when the site's premium status changes.
