### ISSUE TITLE
Site Settings: Site Grade UI Tweak

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#321]
Some UI tweaks to the Site Grade behavior to make it more user friendly
1. Once the site is successfully upgraded, instead of showing the success message and then still showing the select payment right below it, we should just show the success message and have a "OK" button below it which when clicked, resets the view to its current default state with the explanation message and the payment options below.

I've already added code to hide the payment options upon success. What remains is to add the OK button and hook that button up to reset the current view.

**Comment by gilbert** [comment]
Added.
