### ISSUE TITLE
If a payment is rejected, it should be removed from the payment history

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#323]
Reference: https://www.wepay.com/developer/reference/testing

I tested a scenario where I used the quantity of $3.61, which is the magic quantity where a payment is denied, however in my payment history it says that I paid $3.61 to upgrade my account.  

On the callback that notifies us that the payment was rejected, we should update the site status correctly and remove the entry for the payment history.

From our previous discussions I remember you said that WePay treats it as a success and then later calls back to say it was denied. Are you sure there isn't a pre-approve call that we should make first that returns denied so we don't first think of it as a success and then a failure? The reason I ask is because we need to make sure the logic here is correct and we should only undue the impact of the failed transaction.

For example, if the user was on a recurring monthly payment that has 2 more months and they decide to extend it. Don't we cancel their existing subscription and set up a new one? What happens if the new one fails because the payment was denied?

**Comment by gilbert** [comment]
Updated. There's still a bug with next charge date that I need to fix.
