### ISSUE TITLE
Payment Scenario Conversation

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#327]
What happens if I'm on a monthly or annual recurring payment schedule and then I decide to do a one-time payment for a month or a year. Does it cancel my subscription and put me on a year plan?

It occurs to me, considering that they can cancel the subscription at any time, that we should just offer the recurring payment instead of one time payments to simplify the work on the back end.  What do you think?

**Comment by gilbert** [comment]
Yes, subscription-only would make things easier.

**Comment by onaseef** [comment]
I'm going to do subscription only. 
1. Is there a reason you had set it to 1 year and 3 years?  I set them both to 3 years now, but I'm curious if there's a logic behind your initial choice
2. If you set the credit card debit date for 2 weeks from when they establish a subscription and they cancel before then, I assume it just doesn't charge them at all. Is that correct?

**Comment by gilbert** [comment]
1. Nope, I just randomly picked it.
2. Yes, that is correct.

**Comment by gilbert** [comment]
Updated.
