### ISSUE TITLE
Site Grade Error: Shows the Cancel subscription button even though the site is a Standard Site

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#329]
http://www.deelmob.com  aatest25@mailinator.com 123123
1. Go to the site manager and select any of the sites there. You will notice all of the site are of type "Standard", however they all have the isSubscribed value true and if you click on unSubscribe, it shows the error message: Error: no_subscription.
2. The error message should be i18n. 
3. If the user clicks on Cancel Subscription and the error is that there is no subscription we can handle that as if the subscription was successfully cancelled because for all practical purposes the subscription is gone.

**Comment by gilbert** [comment]
This specific error is now treated as a success. I haven't cleared payments yet, and the subscription button isn't showing up, so all the recent logic changes probably fixed the problem.
