### ISSUE TITLE
Site Upgrade doesn't work

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#331]
www.deelmob.com aatest24@mailinator.com 123123

Go to https://www.wepay.com/developer/reference/testing to get  CC numbers

Go to site settings and select aatest24 to upgrade the site grade and leave the autopay monthly selected ad go through the payment process.  At the end, it says the site has been successfully upgraded but the site type remains "Standard".

**Comment by gilbert** [comment]
I'm still working out some kinks in the subscription logic.

**Comment by onaseef** [comment]
Thank you for the update.

You may already be doing this, but it doesn't hurt to be redundant. I want to make sure we handle this scenario correctly:

A user pays for a yearly subscription and in the middle of it, they decide to renew it on a monthly or yearly basis. Since they still have time left, we don't want to short-change them. We should set the next payment date for the day before their premium account is set to expire.

**Comment by gilbert** [comment]
Yup, that's how it's set to work.

**Comment by gilbert** [comment]
Would it be a problem if I cleared all payments on staging?

**Comment by onaseef** [comment]
No, that's fine. I thought that might be what we need to do, though I figured the current state would give you a chance to test boundary conditions.

**Comment by gilbert** [comment]
Ok, I think everything's working now. Subscribing and canceling are working on staging.
