### ISSUE TITLE
PRODUCTION BUG: Custom Page doesn't save

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#332]
http://www.yomobi.com  ymtest@mail.com 123123

I'm using Chrome on my Mac.  See: http://ge.tt/3odf6zI/v/0?c

Drop in a custom page widget. First, notice that the warning icon appears.  Second, type in one short line like: "hello world"

Hit save, then click on "View Mobile Site".  Notice how the text you typed in doesn't appear.

If you go back to the editor and hit enter and type in another line, that line appears, but the first line still doesn't.

**Comment by gilbert** [comment]
Fixed.

**Comment by gilbert** [comment]
Wait, never mind. I just found another edge case.

**Comment by gilbert** [comment]
Ok, fixed.
