### ISSUE TITLE
master: i18n edit-settings.js line 3

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#338]
In the master branch, edit-settings.js,the text currently reads: 

var companyNameErrorText = 'Company name must be at least 2 characters and at least ' +
                              g.MAX_COMPANY_NAME_LENGTH +' characters';

We need to i18n this with max_company_name_length passed in as a variable in the string.

**Comment by gilbert** [comment]
Did this error pop up somehow? The text field has a max length, so it shouldn't happen unless something weird is going on.

**Comment by onaseef** [comment]
The error didn't popup. I was just browsing the code when I saw it. If it never appears I guess we're fine.
