### ISSUE TITLE
master: i18n: /account-setup/3 & General Settings

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#339]
On master branch, choose file control on /account-setup/3  and General Settings should be i18n.  Right now the button "Choose File" and the status: "No file chosen" are in english

**Comment by gilbert** [comment]
That text is pre-defined by the browser and can't be changed. One solution might be to add a "Choose a file" label right above it.

**Comment by onaseef** [comment]
It's fine the way it is i that case.
