### ISSUE TITLE
Revise Category widget instead of creating new List Widget

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#34]
It occurs to me that the Category widget has basically all the functionality I want in the list widget, with one exception. 

If we can add a checkbox in the Category and it's subcategories that says: "Display preview text of items in list view"

When this is checked, the first 3 lines of text from the page would show up in the list view as well.

See emailed image.

**Comment by gilbert** [comment]
Do you think it would be better to have a single checkbox that affects the entire widget?

**Comment by onaseef** [comment]
Make it a single recursive checkbox.

I've thought about that, but wasn't sure if that was better.  Would the checkbox appear only on the top level and than disappear at the subcategory level?

**Comment by gilbert** [comment]
I was thinking on the same page as the "Click Here to Start Editing" button, with a help bubble to explain what it means.

**Comment by onaseef** [comment]
That's a good idea.   We could put it there. 

Please add a special class around the preview text so we can customize the font size, etc.
