### ISSUE TITLE
production: change the way images are edited in the editor

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#344]
In the custom page editor, the way it works now where we click on an image one time to bring up the image edit is turning out to be way too problematic for users. 

We need to change this to where the "add image" button now becomes an "Add / Edit Image" button and if an image is highlighted, when the user clicks on the button, it brings up the image editor.  If no image is selected, it brings up the new image dialog.

**Comment by onaseef** [comment]
What are you thoughts on this? Is it fairy straightforward?

**Comment by gilbert** [comment]
I thought it wouldn't be, but then I discovered an easy way of doing it.

**Comment by onaseef** [comment]
I just tried this on chrome on my mac, and the change doesn't do anything to the image itself. When you make a chance and hit save, it add some broken image, while the selected image is unchanged.

**Comment by onaseef** [comment]
On Firefox the selected image disappears entirely when you hit save.

**Comment by gilbert** [comment]
Oops, sorry about that.

**Comment by onaseef** [comment]
On IE 8 on Windows XP, you have to click the img twice before it gets selected.  Not sure if something simple can be done about this.

**Comment by onaseef** [comment]
We discussed this and it doesn't seem there's much of a choice. IE requires 2 clicks to work.
