### ISSUE TITLE
locale other than en or es doesn't work

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#345]
I added a fr.yml file and when i set the locale=fr or I change my browser settings so french is the default, i don't see any changes.

I looked at the code in application_controller.rb 

  def set_locale
    lang = (request.env['HTTP_ACCEPT_LANGUAGE'] || '').scan(/^[a-z]{2}/).first
    lang = nil unless lang && lang.match(/^(es)$/)

The second line seems to limit the http accept language to spanish only, when it should accept whatever language is there. Am I reading this wrong?

The way the logic should work is that we accept whatever language we get in the header, and then if we can't find the corresponding .yml file, we'd revert back to en.yml

**Comment by gilbert** [comment]
You're reading it correctly. This check happens on every request, so we don't want to do something slow like a filesystem check for yml files.
