### ISSUE TITLE
production: replace the image size text field with a dropdown

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#346]
In the custom page editor, when we add a photo, the image size is field is a text field in the editor. that is not convenient for use. we should replace it with a dropdown that has the options 100% - 10% in 10% increments in descending order. 

It would need to be i18n, and instead of having the % outside, the text in the select field would be 10% 20%, etc.

For backwards compatibility, I imagine we should just round the current size to the  nearest value between 10 and 100

**Comment by gilbert** [comment]
Added.

**Comment by onaseef** [comment]
The dropdown should be in reverse order from 100% down to 10% and it should default to 100%. Right now it defaults to 10%, which means that any time you add a picture, it is automatically shrunk down to 10% on save.

**Comment by gilbert** [comment]
Updated.
