### ISSUE TITLE
deelmob - wepay iframe not appearing

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#348]
www.deelmob.com aatest25@mailinator.com 123123

i tried to upgrade the site aatest24 and get the following error in the javascript.  not sure if it is wepay or us, so i emailed them, but if your'e working tonight, it doesn't hurt to check.

Failed to load resource: the server responded with a status of 503 (Service Unavailable) http://www.deelmob.com/sites/28/upgrade
Uncaught SyntaxError: Unexpected token < 

Would you also check in spanish mode, because i know it adds the ?locale=es to the URL and that might impact the behavior of wepay in the response URL.

POST http://www.deelmob.com/sites/28/upgrade 503 (Service Unavailable) jquery-1.6.2.min.js:18
f.support.ajax.f.ajaxTransport.send jquery-1.6.2.min.js:18
f.extend.ajax jquery-1.6.2.min.js:18
$.rails.rails.ajax rails.js:99
$.rails.rails.handleRemote rails.js:154
(anonymous function) rails.js:344
M jquery-1.6.2.min.js:16
f.event.handle jquery-1.6.2.min.js:17
f.event.add.i.handle.k jquery-1.6.2.min.js:16
Uncaught SyntaxError: Unexpected token < jquery-1.6.2.min.js:16
e.extend.parseJSON jquery-1.6.2.min.js:16
Backbone.View.extend.render.$.bind.site.set.justCancelled site-manager.js:261
f.event.handle jquery-1.6.2.min.js:17
f.event.add.i.handle.k jquery-1.6.2.min.js:16
f.event.trigger jquery-1.6.2.min.js:17
f.fn.extend.trigger jquery-1.6.2.min.js:17
e.extend.each jquery-1.6.2.min.js:16
e.fn.e.each jquery-1.6.2.min.js:16
f.fn.extend.trigger jquery-1.6.2.min.js:17
$.rails.rails.handleRemote.options.error rails.js:148
f.extend._Deferred.e.resolveWith jquery-1.6.2.min.js:16
w jquery-1.6.2.min.js:18
f.support.ajax.f.ajaxTransport.send.d

**Comment by onaseef** [comment]
FYI, I forwarded you an email from WePay about this.

**Comment by gilbert** [comment]
Updated and fixed.
