### ISSUE TITLE
production bug: find-us map image doesn't show up on iphone when wifi turned off

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#350]
From your iphone, with wifi turned off, check out skydivetemple.com and shandeez.com.  On the mobile site, when I click on Find Us, the map image is a broken image link, instead of the map, the way it used to come up.

Have we changed something that would break this feature?

**Comment by gilbert** [comment]
Nothing has changed related to this feature. It seems to work fine for me without wifi. Are you loading the whole page without wifi? It's possible that your phone reception might be poor.

**Comment by onaseef** [comment]
I am loading the whole page without wifi. I also went outside and tried it with different reception and it didn't work any better. Is it possible a security or threshold-limits issue, where google rejects the request because of too many requests from a specific machine?

**Comment by gilbert** [comment]
I honestly don't know. It's very strange how it works with wifi and not without. Have you tried turning safari developer bar on and seeing if there's an error?

**Comment by onaseef** [comment]
It hasn't happened since.
