### ISSUE TITLE
master: js error when trying to save page with photo

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#354]
i pushed the changes to master to staging to test, and on IE8 on XP, when I add a photo and try to save, I get a javascript error that says: 'undefined' is null or not an object jquery-1.6.2.min.js line 16. See; http://ge.tt/3Cj9jFJ/v/0?c

You should be able to duplicate this issue by adding photos and navigating away from the page, then going back and selecting them and editing their size or URL, etc, and then saving then going out and back in, etc.  It's been very easy for me to get to the JS error.

www.deelmob.com ymtest@mail.com 123123

go to Categoria -> 78ikyk

Try to add a photo to the end of the page and set the photo to left aligned and when you hit save, there's a js error.

**Comment by gilbert** [comment]
Fixed.
