### ISSUE TITLE
IE8: in custom page editor, photo must be clicked twice to select it

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#356]
For some reason, with IE8, the photo has to be clicked twice before it is selected. If you click it only once it won't work.

**Comment by gilbert** [comment]
It looks like IE8 doesn't send a click event on an image unless you click on it after it's "selected". If you want I can make it open up the dialog on the second click for ie8 only.

**Comment by onaseef** [comment]
I'd rather it stay the way it is. Having a dialog pop up on click would be problematic. The better option would be if there was a way on IE8 for the javascript to detect that the picture object was selected. Otherwise, it will just have to remain the way it is.

**Comment by gilbert** [comment]
There isn't, unfortunately. I searched for quite a long time.
