### ISSUE TITLE
master branch: IE 9: When loading a photo into a custom page, the size field is initially blank

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#357]
www.deelmob.com aatest24@mailinator.com 123123

Using IE9 on Windows 7, I added a custom page and added a picture to it, and when the picture loads up, the initial size in the drop down list is blank. It should start out at 100%

See: http://ge.tt/8DXfqLJ/v/0

**Comment by gilbert** [comment]
I don't have access to ie at the moment, but I think this change might fix it.

**Comment by onaseef** [comment]
Seems to work now.
