### ISSUE TITLE
master branch: IE: Dialogs that pop up in custom page should have the focus

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#358]
www.deelmob.com aatest24@mailinator.com 123123

See: http://ge.tt/2z39sLJ/v/0   Notice the selection boxes. That's where the browser thinks the focus is. I think you can do this by handling the dialog open event and selecting a control in the dialog to put the .focus() on.

The following dialog boxes are affected: Add Link, Add Video, Add / Edit Image

In IE 8 & 9, when a photo is selected in the custom page and you click on add / edit photo, the focus isn't on the newly popped up dialog, it remains on the selected item behind it in the editor, so if the dialog overlaps on the selected item, the controls won't work until you put the focus on the dialog because the mouse clicks go to the object below, where the browser seems to think the focus is.  

When the dialog pop ups, the focus should be on one of its controls, perhaps the "OK" button, to take focus away from the item behind it.

**Comment by gilbert** [comment]
Updated.
