### ISSUE TITLE
Add Image dialog: No file selected save error

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#359]
http://www.deelmob.com aatest24@mailinator.com 123123 

I was using IE9 on Windows 7, though I imagine this is true of any browser

In the Add Image dialog, if no file is selected and you hit save, it adds an empty image to the page. Hitting save should just close the dialog if no file is selected. Or the Save button can be disabled, though I'd rather just have save do nothing.

**Comment by gilbert** [comment]
Fixed.
