### ISSUE TITLE
production: replacing individual icons with one file that has all the icons

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#361]
The process of downloading all those icons for the widgets and especially for the change icon dialog is a lot of transactions on the heroku server. 

How much work would it be to change the mechanism to download a single file and use the background position css option?

**Comment by gilbert** [comment]
Try generating a sprite using [this website](http://instantsprite.com/), then email me the results and I'll put it up.

**Comment by onaseef** [comment]
The widget and social share sprite files are here: http://ge.tt/1UivMTJ

Since the sprite file is big, the replacement would just be for the change icon dialog in the builder. I don't think it's practical to aggregate the icon files for the websites because we don't which icons the user will choose and the icon file is just too big to download.

**Comment by gilbert** [comment]
Updated.
