### ISSUE TITLE
premium: 3 hour delay in payment processing question

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#363]
Here's the scenario.

I logged on to deelmob.com as aatest24@mailinator.com 123123

I picked a site that was standard and paid the monthly fee to make it a custom site. then i immediately cancelled the subscription. it showed the site as being a custom site, but the payment hadn't been made yet.

The question is, in the scenario above, the user subscribes and then cancels before the 3 hour window ends, does that first payment go through even though the subscription was cancelled?

I want it to go through so I'd like to confirm that the cancellation only affects future payments and not the payment that is scheduled to be made in 3 hours.

**Comment by gilbert** [comment]
Yes, it does cancel the 3 hour payment. I'll update it so it charges immediately (I just figured out a way how).

**Comment by gilbert** [comment]
Updated.
