### ISSUE TITLE
Premium: Change Icon Dialog needs a size tweak

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#366]
How can I set the height/width of the change icon dialog? With the change to using a sprite, the icons are much bigger so I'd like to increase the width of the dialog. I tried one method of increasing the width but because it seems to happen after the dialog is created and positioned, it wasn't centered in the main window. 

What's the mechanism to set the height and width correctly so that the dialog is centered?

**Comment by gilbert** [comment]
You can view the change I just pushed to edit the width of the dialog to your liking.
