### ISSUE TITLE
premium: error when trying to make a site default

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#367]
www.deelmob.com aatest24@mailinator.com

Go to site settings, select aatest26-test-site-for-me-to_use and click on "make default"  a dialog pops up that says: "Error".  But no details.

**Comment by gilbert** [comment]
Did you delete that site? It's not showing up in the list.

**Comment by gilbert** [comment]
Nevermind, I was logged into the wrong account.

**Comment by gilbert** [comment]
Hmm, seems to work for me. Was it a styled dialog or a browser dialog?

**Comment by onaseef** [comment]
I think it was a browser dialog.

**Comment by onaseef** [comment]
I just tried it now again and it failed with a browser dialog with the error message: We're sorry, something went wrong.

See:  http://ge.tt/1X1iNhJ/v/0

When you log in, you should see aatest24copy is the selected site, then click on aatest26-test-site-for-me-to_use and click on default and you should get the error.

**Comment by gilbert** [comment]
Now I see what's going on: a user could not set a company as default unless he was the owner.

**Comment by onaseef** [comment]
To confirm the logic, since the user doesn't own the site and can be removed as an admin, what does the code do if the user makes a site their default site than loses access to it?  Does it select a new site as default automatically?

**Comment by gilbert** [comment]
Yes it does.
