### ISSUE TITLE
merge broke the upload custom icon feature

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#369]
After the merge, in the change icon dialog, the upload custom icon feature stopped working. Now if you select a file to upload a custom icon, nothing happens.

**Comment by gilbert** [comment]
I'm confused where the custom icon upload feature originally resides. When I revert to the commit on master right before merging with premium, the uploader isn't there. When I switch to premium, it isn't there either.

Somehow when I merged premium into master it shows up. In fact today is the first time I've ever seen it.

**Comment by onaseef** [comment]
The custom icon upload feature originally resides in the customicon branch.  I merged the customicon branch with master on Jun 18th. It is entry a838a4.  You can also see the custom upload feature at yomobi.com  ymtest@mail.com 123123

**Comment by gilbert** [comment]
Fixed.
