### ISSUE TITLE
Merge Bug: Custom Icon loader doesn't allow for more than one file upload

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#370]
The merge broke a fix where in the change icon dialog, you could click on "Upload" multiple times and select a different file to use as the icon. Now, once you upload a file, you can't click on "Upload" again.

**Comment by gilbert** [comment]
Oh ok, I didn't know this feature was in place.

**Comment by gilbert** [comment]
Wait, I may have misread this. Are you saying that once you upload a file, you cannot edit the icon and upload another to replace it?

**Comment by gilbert** [comment]
Never mind, I see what you mean.

**Comment by gilbert** [comment]
Fixed.

**Comment by onaseef** [comment]
On IE8, after I select a file one time, the next time I select a file, it doesn't upload it. I selects it but does nothing.

**Comment by gilbert** [comment]
Fixed.
