### ISSUE TITLE
Please confirm the payment logic is correct

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#373]
I know we initially had a 3 hour window before the payment was process to solve a problem where the request was rejected for being before the current time, and then I thought you changed it back to immediately process upon confirmation.

Then I did the following:

See: http://ge.tt/36bO5qJ

www.deelmob.com aatest24@mailinator.com 123123

Go to site manager
Select aatest24
Click on Site Grade
Choose $5 monthly plan  (CC: 4003830171874018)
Make the payment. 
Notice that the current expiration date was July 15, 2012, and after the payment, the next payment date is Aug 15, which means that I should see a payment for July 15, but I don't see it in the payment history. 

Where did the payment go? I just want to make sure we're not losing payments or doing the logic wrong.

**Comment by gilbert** [comment]
Fixed.
