### ISSUE TITLE
WePay Subscription Logic Questions

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#379]
1. When is the first charge taken for a subscription? 
2. If I approve a payment and then immediately cancel the subscription, is the first charge always made? I ask because if the first charge isn't made, the code still has the site as upgraded until the expiration date.
3. If I renew an existing subscription, I thought it cancelled the current subscription and started a new one. Is that correct? I did a monthly subscription on one site and then immediately extended the subscription, and the subscription expiration date changed from 2017 to 2023, which means it added the subscription on to the existing one.  Is that logic correct?
4. If the logic is correct, it means both subscriptions are running simultaneously. How would a user cancel the previous subscription?

**Comment by gilbert** [comment]
1 & 2: Yes, the charge is make immediately.

3 & 4: It should cancel the previous subscription. That's a bug.

**Comment by onaseef** [comment]
How do you calculate the next-payment-date and subscription-end-date when renewing an existing subscription and or creating a new subscription on an upgraded account that hasn't yet expired?

**Comment by gilbert** [comment]
The new subscription start date is supposed to be the old subscription's next change date.

**Comment by gilbert** [comment]
Which site did this bug happen for?

**Comment by onaseef** [comment]
deelmob.com aatest25@mailinator.com 123123

Site Manager -> aatest-jonsbakery  

If you expand the Site Grade section you'll see the subscription goes on till 2023

**Comment by gilbert** [comment]
Fixed.
