### ISSUE TITLE
Cancel subscription via the WePay Email doesn't lead to site being updated

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#380]
I was testing the payment mechanism and canceling the subscription using the email I receive from WePay, but nothing seems to update with the sites themselves.

deelmob.com aatest25@mailinator.com 123123

I cancelled the subscription for aatest-jonsbakery using the WePay email, but the site still states it has a subscription.

**Comment by gilbert** [comment]
After reviewing wepay's checkout record states, I noticed there was one state we weren't handling - `revoked` - which is directly related to this problem.

**Comment by onaseef** [comment]
Has this issue been resolved?

**Comment by gilbert** [comment]
I believe so.
