### ISSUE TITLE
Custom Site Expiration Bug

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#381]
www.deelmob.com aatest25@mailinator.com 123123

Go to the site manager and click on site: aatest-jonsbakery *

Notice the expiration date is Jan 01 2012, which is the default manual expiration date. 

The logic needs to be that if the max expiration date is less than now, it should be set to a standard site.

**Comment by gilbert** [comment]
That was my fault, I was modifying the records directly.
