### ISSUE TITLE
Support regional language files

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#384]
Right now we only support the primary language extension es.yml   vs  es-sp.yml  

How much work is it to support both formats so we can support regional variations on a language?

**Comment by gilbert** [comment]
What's the difference? I would think that each one would be treated as a separate language anyway, such as many sites have both US and US-Britain.

**Comment by onaseef** [comment]
How would we handle EN-US versus EN-BR since we only parse the first 2 characters of the language header?

The Accept-Language header is in the format [2-letter-language-code]-[2-letter-country-code-optional]

We'd need to be able to handle the optional country subcodes to support the user request for properly translated files.

So the way I thought it would work is we'd take the full accept-language LL-CC and look for a file of the name ll-cc.yml if that exists use it, otherwise look for ll.yml, otherwise use the default en.yml

Does that make sense?

**Comment by gilbert** [comment]
Yes, that's what I was thinking too. If the language header is in that simple format, I can make it compatible right now.

**Comment by gilbert** [comment]
I found a gem that does exactly this. It's been added.

**Comment by onaseef** [comment]
So with this change, I can just drop in the file es-sp.yml into the directory and it would automatically pick it up?  

And if we add another language, I'd have to add the primary language to the list eg: { en es fr } and then drop the file fr.yml into the directory?

**Comment by onaseef** [comment]
I added es-es.yml and set firefox to Spanish-Spain which has header es-es and it didn't use the es-es.yml. Instead it used es.yml

**Comment by gilbert** [comment]
Ok, it took me a while to figure this out, but it turns out the problem was very simple:
- First, I renamed `es-es.yml` to `es-ES.yml` for better practice.
- Despite this, the file name does not actually matter. What's important is the first indentation level of the file:

``` yml
# Sample localization file for Spanish. Add more files in this directory for other locales.
# See http://github.com/svenfuchs/rails-i18n/tree/master/rails%2Flocale for starting points.

es-ES:
  powered_by:
    # ...
```
- `es-ES:` used to be `es:`, which is why rails was not detecting it. Make sure this is correct, and it'll all work as expected.
