### ISSUE TITLE
IE8: JS Null Error: Advanced customization editor doesn't show up 

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#385]
www.deelmob.com - aatest29@mailinator.com 123123

The advanced customization editor doesn't show up at all in IE8 on Windows when in Spanish language mode. There is a "undefined" object error involving colorpicker.js

See:  ge.tt/6FFiCIK

**Comment by gilbert** [comment]
I don't have ie8, but I'll check it on 7 and 9 and see if I can duplicate the problem.

**Comment by onaseef** [comment]
I'm guessing you should be able to duplicate it on IE7. It seemed to work fine on IE9

**Comment by gilbert** [comment]
I finally got an ie8 virtual machine to work on my windows box. The bad news is that I can't reproduce the error. It works on both deelmob and my local server.

**Comment by onaseef** [comment]
This issue seems to occur in IE8 when you are in locale=es. It works in locale=en

**Comment by gilbert** [comment]
Turns out the problem was a hanging anchor tag in a locale file. IE chokes on these sometimes, so always remember to close your tags :)
