### ISSUE TITLE
Banner image not appearing in "View Mobile Site" view

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#387]
www.deelmob.com aatest29@mailinator.com 123123

I went to the Site Manager and added a site header image to site jrtransport3. The image appears in the mobile site emulator but not on the mobile site itself.

**Comment by gilbert** [comment]
Fixed.

**Comment by onaseef** [comment]
Did you synch the changes? I'm not seeing them on my master branch

**Comment by gilbert** [comment]
My mistake, I put them on premium. They're in master now.
