### ISSUE TITLE
Mobile Site Height Calculator Bug in Emulator

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#390]
www.deelmob.com aatest25.mailinator.com 123123

Go to Site Manager and select aatest25copy to edit.

Go to the website builder and click on Advanced Customization. 

The banner image size is currently set to 10%.  

Make it 100% and notice how the bottom of the site is now cut off and cannot be scrolled to.

**Comment by gilbert** [comment]
Yeah, it's pretty important. I did fix the problem.
