### ISSUE TITLE
Invalid Subscription Date

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#398]
See http://ge.tt/8v9ATSK/v/0?c

www.deelmob.com jrtransport@mailinator.com 123123

I'm testing out the WePay logic by doing variations on subscribing and renewing. So, for example:
1. I signed up for the monthly subscription using a valid credit card number. It was successful.
2. I cancelled the subscription.
3. I signed up for an annual subscription, and the date was 6 years out, instead of 5.

Please play around with the payment system trying various scenarios like I am  and see what you find.

**Comment by gilbert** [comment]
Fixed.

**Comment by onaseef** [comment]
www.deelmob.com jrtransport@mailinator.com 123123

Go to Site Manager
Click on Site Grade
Upgrade using the annual plan. The expiration date is correct at 2017
Without canceling the subscription, click Renew Subscription with the annual option. 
The expiration date is incorrect at 2018.
