### ISSUE TITLE
Cancel Subscription Fails

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#399]
www.deelmob.com aatest25@mailinator.com 123123

Select site aatest25copy to edit

Click on Cancel Subscription. It fails with an error, and in the javascript console, we get the error below. I'm guessing this is related to the fact that the subscription was created in staging. 

My concern is that perhaps we aren't handling an error case we should be. Users should always be able to cancel their subscription. In this case, when they try to cancel and it returns an error, should we have a way to check the status and treat a missing subscription record the same as a successful cancel for UI purposes?

POST http://www.deelmob.com/sites/28/cancel_sub 400 (Bad Request) jquery-1.6.4.min.js:4
f.support.ajax.f.ajaxTransport.send jquery-1.6.4.min.js:4
f.extend.ajax jquery-1.6.4.min.js:4
$.rails.rails.ajax rails.js:99
$.rails.rails.handleRemote rails.js:154
(anonymous function) rails.js:344
L jquery-1.6.4.min.js:2
f.event.handle jquery-1.6.4.min.js:3
f.event.add.i.handle.k

**Comment by onaseef** [comment]
You can easily duplicate this error by following these steps:
1. www.deelmob.com aatest25@mailinator.com 123123
2. Go to the Site Manager
3. Select site aatest24copy (2nd from top)
4. Click on Site Grade
5. Click "Cancel Subscription"
6. See the bad request in the JS Console

**Comment by onaseef** [comment]
Here is what shows up in the heroku logs for this request: 

CANCEL ERROR: An error occurred: {:error=>"invalid_request", :error_description=>"invalid preapproval_id"}::#<WepayRails::Exceptions::WepayCheckoutError: An error occurred: {:error=>"invalid_request", :error_description=>"invalid preapproval_id"}>

I would imagine in this situation that since the preapproval id is invalide, that the subscription no longer exists, so it can be treated as successfully cancelled.

I think the reason this happened is because the initial subscription was made on the heroku staging server rather than the production server.

In cases where a pre-approval id is invalid, we should treat it as if the subscription was cancelled and just keep the expiration date.

For me, the primary issues are:
1. The front end should indicate the subscription is cancelled if the preapproval_id is invalid because it means there is no subscription.
2. Users should never feel like they can't cancel their subscription.

**Comment by gilbert** [comment]
Agreed. That's what it does now in other similar cases, such as when it's already been cancelled.

**Comment by onaseef** [comment]
Can we handle this scenario such that if wepay returns "invalid prepay authorization" we treat it as a successful cancel.

**Comment by gilbert** [comment]
Sure

**Comment by onaseef** [comment]
Also, if we poll to see the status and it comes back as invalid prepay auth, we'd need to set the front end to indicate there is no subscription and set the expiration date to the next payment date.

**Comment by gilbert** [comment]
Wait, I'm a little confused. Did the "invalid prepay authorization" error appear when you tried to cancel a subscription?

YoMobi does no polling; it only updates WePay data when WePay tells it to through IPN.

**Comment by onaseef** [comment]
If you follow the directions in the github notes you'll see the error. It occurred when I tried to cancel a subscription that might have been set up on the test server. So that may be why it was a bad pre-auth code. 

Regardless of how we end up with a bad pre-auth code, the cancel operation on yomobi should appear successful

**Comment by gilbert** [comment]
Oh ok, that's how it's being handled.
