### ISSUE TITLE
Image covered by text and other images get resized too small.

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#40]
The text overlaps the picture.  See emailed image.  

In category-like widgets such as "Products", if you only add items to the list and those items have a long description, the image that is uploaded is displayed in a smaller size than it should be. See emailed image.

I'm using account: http://local.host:3000/preview/local, and the specific page is:

http://local.host:3000/preview/local#page/Services/i676-auhzpvfy

Also, in general, with items in category-like widgets, we're having all sorts of issues if there is a mix of items with long descriptions and photos.

**Comment by gilbert** [comment]
I don't think there is a way to get the resizing you want. A fixed width on the image column seems like the best compromise.

**Comment by onaseef** [comment]
Is it a result of using the pre tag, because it works fine everywhere else?

If so, we might just have to get rid of the pre tag. A fixed width would only be okay if we resize all the images to the exact same width, even if they are smaller than the fixed width

**Comment by gilbert** [comment]
Removing the pre tag might work. Resizing the images is easy, but smaller ones will look pixelated.

**Comment by gilbert** [comment]
Ok, removing the pre tag doesn't work after all.

**Comment by onaseef** [comment]
Why does it work with long names in a subcategory?  I'm trying to understand what the difference is between the two?  Basically, if you add a single subcategory to a list with items, it wraps correctly and looks great.  It's only if we have items with no subcategories that it sizes wrong.

**Comment by onaseef** [comment]
Another question: why do we use img-col in some places, but wphoto in others?

**Comment by onaseef** [comment]
It turns out if in items, you replace the class "wphoto" with "img-col", the problem is solved.

**Comment by gilbert** [comment]
Yeah I just tried that and discovered the same thing. To answer your question, they differed because they were implemented at different times with different specs.
