### ISSUE TITLE
JS console Error Question

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#403]
When using the Wepay iFrame to pay for a site, I see the following:

Unsafe JavaScript attempt to access frame with URL http://www.deelmob.com/site-manager from frame with URL https://www.wepay.com/flow/confirm_cc/3504017?iframe=1. Domains, protocols and ports must match.

Is this of any significance, since it says domains, protocols and ports must match?

**Comment by gilbert** [comment]
It's only a warning about the browser's same-origin policies. It's not harmful and can't really be suppressed.
