### ISSUE TITLE
Add WePay preapproval_id  to the Payment History table

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#408]
WePay uses the preapproval_id to troubleshoot issues with payments, so if there's a problem with a user's account, they will need easy access to this number to deal with WePay.

The preapproval_id is part of the URL parameters returned by WePay after the user pays. We should store it in the payment record.

**Comment by gilbert** [comment]
Every WePay variable is stored in the `wepay_checkout_records` table. The payment record has a wepay_checkout_record_id pointing to its corresponding one.

**Comment by onaseef** [comment]
What I mean is, please expose it in the payment history table in the account settings view.

**Comment by gilbert** [comment]
Updated.
