### ISSUE TITLE
WePay Payment Failure Handling

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#409]
Do we properly handle the case where the pre-authorization goes through successfully but the payment later fails?

The situation would be as follows:
1. User pays to upgrade
2. Pre-Auth succeeds so we treat the site as upgraded
3. WePay notifies us that the actual payment failed

At that point, we need to reverse the transaction and make sure the upgrade end date is correct since we never received a payment.

**Comment by gilbert** [comment]
Yes, this is handled in `wepay_checkout_record_obvserver.rb:56`

**Comment by onaseef** [comment]
I have been doing a bunch of testing with invalid payment information that gets preapproved but never leads to a charge. I have yet to see any emails indicating the charge failed, nor have I see any sites go back to being standard sites.

I see this: wepay_checkout_record_obvserver.rb

```
when /^(failed|refunded|chargeback)$/ then
  payment.is_valid = false
  UserMailer.notify_bad_payment(payment, wcr.state).deliver
```

But where is the subscription cancellation step and setting the expiration date on the site?

**Comment by gilbert** [comment]
That's handled on line 92:

```
payment.company.recalculate_premium
```

Payments with `is_valid == false` are completely ignored when calculating expiration dates and premium statuses.

**Comment by onaseef** [comment]
I think what may be happening is that I set up the subscription and then immediately cancel it. We see a pre-approval id and treat it like a success, but no charge is ever made to the CC and no notification comes in that the charge failed because i cancelled it before wepay actually tries to charge the card.

So in essence a user can get a free subscription.  

What needs to happen when an account is cancelled at any time is that we check when the last payment was _received_ rather than just authorized, and calculate from there based on the term.

**Comment by onaseef** [comment]
Basically, we can set the account to premium upon successful authorization, but we also need to store when the last payment was received, and if the user chooses to cancel on our side or through WePay's email, we calculate the status based on:

case wcr.state
  when /^(|captured|settled)$/ then 
  last-payment-received-date = NOW
  payment.is_valid = true

The last-payment-received-date would only be used when a user cancels or wepay tells us a payment failed. Otherwise, we treat the pre-auth as a success.

**Comment by gilbert** [comment]
If WePay isn't making an IPN on a cancelled charge, then you need to contact them about it. That's a bug on their end, and they are probably very interested in fixing it.

In theory, if the user cancels before the card gets charge, WePay should update its record to one of the failed states and send an IPN to YoMobi. It's true that YoMobi treats a payment authorization as a success, but it also invalidates a payment if something goes wrong, setting the site to non-premium if applicable.

**Comment by onaseef** [comment]
The problem is the process:
1. We request pre-approval, which succeeds
2. We then treat that pre-approval as if a payment was made
3. WePay hasn't had time to actually settle the payment
4. The user cancels the request on our side, so we send a cancel-authorization, which succeeds
5. Since WePay never had occasion to process the payment, it has no reason to send us a payment-failed or user-cancelled IPN. The fact that it notified us of success when we request to cancel the subscription is all we get.

That is the case we aren't handling properly, when we successfully request a cancel and therefore get no IPN.

**Comment by onaseef** [comment]
We can treat the pre-auth as a success. What needs to change is that we also need to track when the last time we actually received a payment was.   So in wepay_checkout_record_observer, we'd add the line:

when /^(|captured|settled)$/ then  last-payment-received-date = NOW

We'd store that with the site record in the database.

It also means we need to call recalculate_premium when we initiate the cancel, not just when we get a WePay IPN of cancel.

Then, in recalculate_premium:

premium-end-date = (last-payement-received-date == NULL) ? NOW :  last-payment-received-date + TERM

**Comment by onaseef** [comment]
FYI, wepay does send a cancelled-authorization when you cancel using the email you receive. However, it doesn't send an IPN when we request the cancel ourselves because the immediate response we get back counts as the notification, so we will need to handle that case.

**Comment by gilbert** [comment]
Ok, I understand the problem now. I'll get it fixed pretty soon.

**Comment by onaseef** [comment]
How is last-payment-received used?  

Do you use it to determine if a payment is valid? Is there a last-payment-date for each authorization?

I see that you do set the last payment date to NOW when a payment is received, but I'm not seeing how it is used otherwise.

I just want to make sure this scenario is covered correctly:

last-payment-date = NULL

May 1, 2012 - user starts monthly subscription:  Upgrade expiration date = May 30, 2012
May 2, 2012 - Wepay notifies us that payment was captured:  last-payment-date = May 2, 2012
May 10, 2012 - user cancels subscription: Upgrade expiration date = May 30, 2012
May 15, 2012 - user starts annual subscription: upgrade expiration date = May 15, 2013
May 15, 2012 - user immediately cancels annual subscription (no IPN from WePay)

The code checks if  last-payment-date == NULL.  It is not NULL, so what happens?

**Comment by gilbert** [comment]
It's used in `wepay_checkout_record_observer.rb:87`. It's during a user cancel; it marks a payment record as invalid if an actual payment has not been received.

As for that scenario, I'm not sure. This is a perfect example of where automated testing comes into play. I'll write a test for this scenario in a bit.

**Comment by gilbert** [comment]
Actually, upon re-reading your scenario, the annual subscription will just be marked as invalid. No payment was received, and it didn't start in the first place. This scenario has been covered for a while now.

**Comment by gilbert** [comment]
To conclude, the annual subscription is invalidated, and the site expiration date goes back to what it was (May 30th in your scenario).
