### ISSUE TITLE
Advanced Customization Link Fails

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#410]
www.deelmob.com aatest25@mailinator.com

Edit Site aatest24copy

Click on Advanced Customization
Click on the header in the emulator. That changes the editor view to the header editor view, but it doesn't update the URL.
Click on Advanced Customization. Nothing happens. 

You have to click on something that changes the URL to make Advanced Customization link work again.

**Comment by gilbert** [comment]
When you say header, do you mean the mobile tab bar? If so, what browser are you using?

**Comment by onaseef** [comment]
I mean the header which has the site name, logo & photo not the tab bar. The very top part of the mobile site

**Comment by gilbert** [comment]
Fixed.
