### ISSUE TITLE
WePay Cancel Subscription Bug - Site Grade state is invalid

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#411]
www.deelmob.com aatest29@mailinator.com 123123

Go to Site Manager
Select site jrtransport2-2 to upgrade.
Select the monthly payment and make a payment

Cancel the subscription.  It cancels successfully, but the Site Grade message is:
Custom (expires: Jan 01, 2012)  It should be Standard

I've also seen an error where  in the javascript console it says it can't load resources, but i can't reliably duplicate it.

**Comment by gilbert** [comment]
Fixed.
