### ISSUE TITLE
Too much white space at bottom - More accurately calculate height of a mobile page

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#412]
If you go on your phone to http://aatest24copy.deelmob.com/, it takes you to a sample mobile site for Connecther. If you notice at the bottom, there is a lot of white space when it renders. 

If you go to www.deelmob.com aatest25@mailinator.com 123123 and look in the emulator for the same site, the trailing space is much better. 

Can we do the same height calculation in the mobile site as in the emulator and preview?

**Comment by gilbert** [comment]
Fixed.

**Comment by onaseef** [comment]
The white space on aatest24copy improved, but there's still a lot on this one:

http://aatest-jonsbakery.deelmob.com

**Comment by gilbert** [comment]
That's because ads are supposed to be showing up since it's a standard site. If the ads are there, it'll look normal.

**Comment by onaseef** [comment]
Are the ads not showing up because it's on development?

**Comment by gilbert** [comment]
Correct
