### ISSUE TITLE
deelmob: generates badly formatted sitekey url when in spanish language mode

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#413]
I put my site in spanish language mode, when to the site administrator and generated a sitekey URL, this is what I got:

http://www.deelmob.com/users/sign_up?locale=es?sk=nolz6wfgu4h39je9mhwff9v8ftp39c3p

Notice the 2 ? in the URL.

**Comment by onaseef** [comment]
We need to add a check to site_manager_controller.rb line 209 

:key => "#{new_user_registration_url}?sk=#{key}" }

because in spanish language mode, the URL has a ?locale=es attached to it. 

It would make sense to have a generic utility function: add parameter to URL, which checks the current URL format and adds a parameter appropriately

**Comment by gilbert** [comment]
Fixed.
