### ISSUE TITLE
Site doesn't properly handle preferred-language header

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#417]
I recall we made changes that were supposed to improve the way the site handles the preferred-language header. I just set Firefox on Windows to the language: Spanish-Paraguay (es-py) and the translated site doesn't come up.

If I set it to just spanish (es), it works fine. It also handles es-es fine.  I thought that the code would check the most appropriate language and return that.

**Comment by gilbert** [comment]
Any new language you need to add to `application.rb:30`.

**Comment by onaseef** [comment]
So, even if we don't have a language file specific to es-py, i should add it to application.rb and it will pick es.yml file instead?
