### ISSUE TITLE
Error when trying to run the code on my local machine

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#419]
I get the following error when I try to run YoMobi locally:

---

NameError in BuilderController#index

undefined local variable or method `http_accept_language' for #BuilderController:0x007f8c35aa1400
Rails.root: /Users/Omar/yomobi

Application Trace | Framework Trace | Full Trace
app/controllers/application_controller.rb:75:in `set_locale'

---

I tried to do a rake db:migrate and got the following error:

omba:yomobi Omar$ rake db:migrate
(in /Users/Omar/yomobi)
/usr/local/Cellar/ruby/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/file_utils.rb:10: warning: already initialized constant RUBY
/usr/local/Cellar/ruby/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/file_utils.rb:84: warning: already initialized constant LN_SUPPORTED
==  RequirePaymentExpireDate: migrating =======================================
-- change_column(:payments, :expire_date, :date, {:null=>false})
rake aborted!
An error has occurred, this and all later migrations canceled:

payments.expire_date may not be NULL

**Comment by onaseef** [comment]
I get the same error when I push the latest master code to the staging server.

**Comment by gilbert** [comment]
Fixed. Not sure how that happened, but it should be ok now.
