### ISSUE TITLE
Add an anchor to the site-manager URL so it will open a specific section

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#423]
I'd like to be able to have users click on the Upgrade ad in the mobile phone emulator and go directly to the site manager with the "Upgrade" section open.

It's easy enough to get to the site-manager using the URL, but there's no way to have the Upgrade section already open. 

Can we add a URL element that will open the individual sections of the site-manager

Maybe something like site-manager?expand=1 where 1 is the index of the section to expand

**Comment by onaseef** [comment]
FYI, I added a temporary workaround to make the upgrade section open automatically, however it would be good to have a way to open the other sections too via the URL.

**Comment by gilbert** [comment]
I added it to the url. In browsers that support it, the url will update when a new section is opened.
