### ISSUE TITLE
Create individual titles, keywords and descriptions for the various pages

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#424]
Right now, all of the pages share the same title, keywords and descriptions. The SEO company we're working with wants us to use different keywords and descriptions for each of the pre-login pages. How can this be done?

Also, how do I get more access to the help.yomobi.com environment so I can add titles, keywords, descriptions, and CSS there?

**Comment by gilbert** [comment]
1. It would have to be done with each individual page. It's probably possible to factor this into a yml file.
2. If you create another private repository for help.yomobi.com and give me access, I'll push the content to it and give you instructions on where to change certain things.

**Comment by onaseef** [comment]
I figured it would be on an page by page basis. Can you set it up to work that way so I can get the SEO started. It doesn't need to be a YML format, unless that's the better option. 

I'll create a repository and let you know when it's ready.

**Comment by gilbert** [comment]
Ok, updated. If you look in home_controller.rb:42, you'll see the two meta tags that you can customize per page. That file should contain most if not all the non-logged in pages.

**Comment by onaseef** [comment]
Thanks. Does it include title, keywords and description? Those are the 3 we need access to.

**Comment by gilbert** [comment]
Yes. I just added title.

**Comment by onaseef** [comment]
Excellent work! 

How would I access the /users/sign_up page to modify the meta there?  I think everything is based on the routes.rb file and I don't see a route for users/sign_up

**Comment by gilbert** [comment]
It's the one in sessions_controller.rb

**Comment by onaseef** [comment]
What do I put in sessions_controller.rb to change the title and meta information  for /users/sign_up?
