### ISSUE TITLE
Adding New Widget Scrolls to the middle of the page instead of the bottom

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#426]
www.deelmob.com - aatest29@mailinator.com 123123

Scroll down to the bottom of the site jrtransport and add a widget.  Adding a widget makes the site scroll to the center, hiding the newly added widget from view.

Also, if you scroll the site to the top and drop in a widget, the site only scrolls halfway down, making the newly added widget still not visible.

**Comment by onaseef** [comment]
The issue seems to be that it isn't calculating the height correctly.

**Comment by gilbert** [comment]
Fixed.
