### ISSUE TITLE
Keep Me Informed Widget URL encode's a ' in the mobile form

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#428]
http://www.deelmob.com aatest29@mailinator.com 123123

In the Keep Me Informed widget in the builder, the name "JR's Personal..." correctly has the '

If you click on "View Mobile Site"  -> Keep Me Informed, the ' is replaced with &#39;

I can't remember if we did a URL encode fo this because it was causing a crash somewhere else in the site, so when fixing this, we want to make sure not to break something else.

**Comment by gilbert** [comment]
Fixed.
