### ISSUE TITLE
Keep Me Informed (and all form pages) jump to very top of site after successfully sending information

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#429]
If you visit jrtransport.deelmob.com and fill out your email address in Keep Me Informed and then click on Send, after it succeeds, it jumps to the very top of the site, so you have to scroll back down to see the message that reads:

Thank you for following JR&#39;s Personal Transport Systems.

The same happens with Call Me Back, Booking Request, and Leave a Message

**Comment by gilbert** [comment]
Fixed.
