### ISSUE TITLE
Add a checkbox to the Link editor that suppresses the redirect

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#430]
We need to add a checkbox to the "Link" editor in the mobile site builder that says:  "Do not redirect"

The checkbox would appear below the Link field.

When checked, the "Link" widget behaves exactly the same as the Full Website widget, it suppresses the redirect.

**Comment by onaseef** [comment]
I don't think I did this correctly. Gilbert, would you please verify this is done right.

**Comment by gilbert** [comment]
It looks correct to me. Nice job.
