### ISSUE TITLE
Full Website Link doesn't seem to work with https

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#431]
Visit ComSecLLC.com on your iPhone and click on the full website link. It doesn't work. It keeps redirecting back to the mobile version of the site.

**Comment by gilbert** [comment]
Yes, that's not going to work unless YoMobi also has a SSL certificate (the desktop redirect code needs to be https).

**Comment by onaseef** [comment]
How easy is it to fix if I get an SSL certificate for yomobi?

**Comment by gilbert** [comment]
I _think_ if you follow [heroku's ssl instructions](https://devcenter.heroku.com/articles/ssl), you should be able to start accessing yomobi pages through https.

**Comment by onaseef** [comment]
I'll look into it.  Why would https keep our cookie from working?

**Comment by gilbert** [comment]
Since their site is about security, they've probably set a server flag to only accept secure cookies.

**Comment by onaseef** [comment]
Good News!

It turns out it has nothing to do with SSL. It's because of the way the URL is capitalized.  On the CompSecLLC.yomobi.com website, the URL in the Full Website widget is spelled: http://www.ComSecLLc.com (with caps). 

I verified this by creating 2 links on ymtest.yomobi.com  On your phone, go to http://ymtest.yomobi.com. Click on the first widget: CompSec with CAPS.  It doesn't work right. Now click on the second one: CompSecLLC NoCaps, and it works right.

I think the issue is that you're not doing a case-insensitive comparison when seeing which sites to exclude.

**Comment by gilbert** [comment]
Got it.

**Comment by onaseef** [comment]
To make sure we've covered various uses cases:

Is it possible that document.domain in mobile_redirect.js.erb line 8 can ever return a non-lowercase string?  Basically, is there a case insensitive comparison option that would make more sense, or does doing tolowercase make more sense, and how would that work with I18N?  I think they were adding localized URLs.

**Comment by gilbert** [comment]
Domains are always lower case, but I added the conversion anyway. i18n shouldn't make a difference in this case.
