### ISSUE TITLE
Please document the steps you use to set up your test environment

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#432]
Please update 

https://github.com/onaseef/yomobi/blob/master/README.md 

and also fill in the details of all the steps you took to set up the development environment in this document:

https://github.com/onaseef/yomobi/wiki/_new?wiki[name]=How%20to%20setup%20a%20development%20Environment

Please be as detailed as possible and document the process from start to finish for future reference

**Comment by esm-zac** [comment]
Updated
