### ISSUE TITLE
Send an email when the user updates their login email in Account Settings

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#44]
If a user updates their login email address in the Account Settings page, we should automatically send an email to their old email and new email indicating that the login email has been updated.

The email should read something like:

The email associated with your YoMobi site (URL) has been changed from <old email> to <new email>. Next time you log in to YoMobi, your login email will be: <new email>.

Thank You,
YoMobi Support

**Comment by gilbert** [comment]
In the process of doing this. What do you want the subject to be?

**Comment by onaseef** [comment]
Your YoMobi account username has changed.
