### ISSUE TITLE
PRODUCTION BUG: Bug with manual expiration date

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#440]
Looking at the site stimfg.yomobi.com:
1. It has a manual expire date of Sept 9, 2012, and we're on the 11th and it did not unexpire as it should using the scheduled heroku task that expires sites.
2. On 9/11, the user paid for a yearly upgrade to the site, and looking at the Payments table, the expire dates are all 2022, instead of 2017.
3. If there is a manual expire date and a payment expire date, does the code user the later date?

FYI, the site needs to remain an upgraded site, so whatever bug fixes are done shouldn't accidentally change the site grade.

**Comment by gilbert** [comment]
1. Fixed and covered by a test.
2. This should be fixed in the future as well.
3. Yes
