### ISSUE TITLE
Delete coch db with company.

### ISSUE THREAD

**Issue by eicca** [onaseef/yomobi#442]
We delete test drive users and their company with a rake task. However couch database doesn't removed with company.

Maybe we can add callback to `Company` model that can do this behavior? Or is there any pitfalls?

**Comment by gilbert** [comment]
Technically speaking, there are no pitfalls. Adding a function to `Company` should be fine.

**Comment by onaseef** [comment]
Mikhail, has this issue been resolved?

**Comment by eicca** [comment]
Yes, already done: https://github.com/onaseef/yomobi/commit/3d5d073800375594c629078c82e450239e8b7ec2
