### ISSUE TITLE
Photo upload progress bar no longer showing on any browser on windows platform

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#54]
It used to show up before, and not anymore.  Did something change?

It wasn't always smooth, which is okay, but there was always some sort of progress indicator.

**Comment by gilbert** [comment]
Which browser did it used to show up on? It seems ok on my ie8, but I'm not sure what exactly you were seeing before and are now.

**Comment by onaseef** [comment]
It used to show up on firefox, safari and IE7 on windows.  It wasn't smooth, but there was some indication of progress. We saw nothing when we tested this evening.

**Comment by gilbert** [comment]
It seems fine on my windows xp ie7 and windows 7 ie8. Are you still seeing this issue?

**Comment by onaseef** [comment]
I am still seeing the issue on IE7 on my Windows XP box.

**Comment by gilbert** [comment]
The only way the progress bar would stop working altogether is if you don't have flash on your machine. In that case it would degrade to html4, which doesn't support the progress bar. The progress bar should still hit 100% once the upload is complete.

**Comment by onaseef** [comment]
My computer does have flash.  Since the upload functionality is working, this is less of a priority than the other functional bugs.  It's more important that we get the basic functionality bug free and than we can continue to tweak.

**Comment by gilbert** [comment]
Covered by issue #73
