### ISSUE TITLE
FireFox Custom Page photo uploader issue

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#70]
In a custom page and in the New Item dialogs, the "Upload" button stops working when you do the following:
1. Add a custom page and add a photo the custom page.
2. Switch to a different widget
3. Come back to the custom page widget
4. Click Remove picture.
5. Click on "Upload" button.  Nothing happens.

**Comment by onaseef** [comment]
Still happens in a Category widget.  It just happened now.  I imagine it has to be adjusted for each widget it's in?

**Comment by gilbert** [comment]
Which category widget, and in what dialog?

**Comment by onaseef** [comment]
Actually, the issue is in Firefox.  I'm in the Menu widget.  The hidden control is mispositioned.  If I click over the Browse button, nothing happens.

But if I move the mouse around until it switches from the pointer to the "text edit" icon and click, than the file browser shows up.

Right now, I have to click over the text "Picture..." in  "Select a Picture..." to get the file browser.

I'm also seeing the issue in the About Us widget.   In that case, the first time I edit the About Us widget, if I click on the bottom half of the "Browse" button nothing happens.  I have to click near the top half of the Browse button, where the mouse changes from a pointer to a text edit icon.

To reproduce:

Log out and close your browser. Than restart FireFox and log in and click on About Us and hover over the browser button.
