### ISSUE TITLE
New Property Listing photo URL bug

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#71]
In the Property Listings widget, if you add a new Property Listing and add a Photo ULR, instead of just storing the URL, something seems to be going on in the background and the URL is converting into something else.

Steps to reproduce:
1. Add the Property Listings Widget
2. Add a New Listing
3. Type in a photo URL.  
4. If you type in cnn.com into the field, the final link is one thing
5. If you type in www.cnn.com, the final link is something else

This field doesn't require any special processing.  Just take the URL the user provides and make it a link as is

**Comment by gilbert** [comment]
Actually, it's the lack of special processing that is causing this. Both css.com and www.cnn.com resolve to urls that are local to yomobi.com; not what we want.
