### ISSUE TITLE
If a category or item already has an image and you just do an upload of a new picture, the photo doesn't upload till you go back and re-enter the category

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#72]
I'm using the "local" site.
I'm in Photo Overlap B -> gigalo page

It already has a photo.  So I just do Upload and picked a new photo. 

The image in the mobile rendered doesn't update till I go out and come back in.

**Comment by gilbert** [comment]
What browser is this happening in? It updates fine for me.

**Comment by onaseef** [comment]
This might be the result of being logged in twice on the same account.
