### ISSUE TITLE
Still not being stripped - On save, we should strip table, td & tr tags from pasted text.

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#75]
http://wonko.com/post/sanitize - this might be helpful.  We can strip everything but a specified list: 

b, h1, h2, h3, u, i, strikethough, p, ul, li, ol, indent, a, hr, strong, blockquote

When we paste text into a custom page or a category page, we already strip style information.  We also need to strip the table, td, tr tags too.

I think you can use the gsub method on string to clear out unwanted tags without losing the data in the tags.  The tags I'd want to remove are:  [CLICK EDIT TO SEE THE TAGS]

<table*>,</table>,<tbody*>,</tbody>,<th*>,</th>,<tr*>,</tr>,<td*>,</td>

The '*' means anything that comes after <table  for example, we should strip <table> as well as <table class="tclass">

**Comment by gilbert** [comment]
It's true that this tool may help, but because it is ruby, it will only work on the server side. In other words, we can't instantly strip the moment the user pastes content; it would happen on save. On the other hand, because it's happening server side, saved content will be guaranteed to be clean.

**Comment by onaseef** [comment]
On the client side, can we use string manipulation to remove tags we don't want, instead.  So we'd take the html that is pasted and do a string.replace("<_table_>, ""), etc.  Can we do that on the client side?

**Comment by gilbert** [comment]
Yes, that's possible. I've been looking into a way to do that.

**Comment by onaseef** [comment]
Table tag not always being stripped.  Perhaps when it has attributes, the string matching doesn't recognize it.

**Comment by gilbert** [comment]
Can you give me an example that causes it not to work? It's currently stripping by the actual tag name, so there's no html string matching going on.

**Comment by onaseef** [comment]
Log in to yomobi.com using un: ymtest@mailinator.com pw:123123

Click on the widget named Category (it's the first one) and then click on My Page.  You'll see that the table, td, tr tags are not being stripped.

To duplicate: 
1. Go to http://shinagawa.ph/about-us/
2. copy the text from the title "About Us" down to the bottom 
3. paste it into a new page.  The tags don't strip.
