### ISSUE TITLE
If you delete a photo from a page using the Delete button in the photo edit dialog the emulator doesn't refresh until after you do something in the editor

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#87]
I added a photo to a page, then I delete it. The emulator didn't update until I click in the editor.

**Comment by gilbert** [comment]
What browser is this happening in? It works fine for me in chrome, safari, firefox 3.6 and firefox latest.

**Comment by onaseef** [comment]
I'm on my Mac, and it happens consistently with chrome.  The emulator doesn't refresh until I click i the editor.

Same thing happens on Safari and FireFox on my Mac.

To reproduce, add a Category and a page.  Put some text in the page.   Add a photo.  Once the photo is added, double-click on the photo to bring up the photo edit dialog. Click delete.  The picture is removed from the text editor but not the emulator.
