### ISSUE TITLE
Photo upload UI tweaks

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#89]
1. Make the order in the postion drop down, Left, Right, Inline with Text, and make Left the default value.
2. Change size row to:  Size:  [3 digit input box] %.  And make 100% the default size. Limit the input field to between 1-100. No less and no more.

**Comment by gilbert** [comment]
Is making the default size 100% a good idea? Smaller images will be pixelated and not look so good.

**Comment by onaseef** [comment]
When I say 100%, I mean the picture should be it's original size, unless it's bigger than the width of a phone, than it should be resized down to the max width of a phone screen and display at 100% of that size.  I don't want the images to be increased in size, i just don't want "original size" for pictures that are super huge.

**Comment by gilbert** [comment]
"Original Size" does enforce the max width of the screen. Or at least it should. Did you find a bug related to this?

**Comment by onaseef** [comment]
Now that I see what 100% means, I understand why you have original size and 100% (fit to screen).  I thought 100% was 100% of the original size.

I didn't think to have pictures be displayed larger than their normal size.  I don't think that looks good.  The behavior I want is that a picture has a maximum size of the lesser of  "width of phone screen" or "its full size width".  

And then the percent is a percent of the size of the image itself, not of the size of the screen.
