### ISSUE TITLE
In Chrome, if a picture is left or right aligned, it can't be deleted with the back button in the editor

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#90]
Use the "local" account for data.
Click on category "Newest"
Click on "A Page with a picture of animals"
Search for the word: iniliK 
Put the cursor right before the letter K and click on "delete".  Nothing happens. The cursor stops moving.  You can use the arrow keys, but the delete button stops before the i and won't delete any more.

The reason is if you look at the HTML, in between i and K is the <img> tag. The editor doesn't know how to handle  it.

**Comment by gilbert** [comment]
This is unavoidable. The same thing happens in tinymce and ckeditor. Not sure what to do.

**Comment by onaseef** [comment]
If we could select the photo and delete it in the editor, that would be helpful.  Because most people think they can delete whatever is after the cursor by hitting the delete button.  

Is that possible?

**Comment by gilbert** [comment]
Oh sorry, I forgot to tell you that you can double click to edit an image. I made it double click to avoid potential conflicts with dragging an image around. I'll see if I can make it single click with no problems.
