### ISSUE TITLE
No way to turn a photo into a link

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#91]
I can't find a way to turn a photo into a link in the editor, especially in Chrome and Safari on the Mac, because there's no way for me to select the picture to do anything with it.

One solution would be to add a "URL" field to the photo uploader, and if they add a URL, you make the picture a link.

**Comment by gilbert** [comment]
It's possible to make a link by text-highlighting the image and clicking the link button, but I'll insert a url field to make it easier.
